// ---------------------------------------------------------------------------
// tests/comments — the claims comments make about the repo, checked
// ---------------------------------------------------------------------------
// A comment cannot be wrong at runtime, so nothing catches it when it goes
// stale — it just quietly misdirects the next reader. These are the three
// classes that have actually broken here, each one a check a machine can make:
// a path that no longer exists, a constant restated in prose, and a citation
// key with no entry.
//
// They read the SOURCE tree, not `dist/`: comments are stripped from the build,
// so there is nothing left to check by the time the rest of the suite runs.

import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** Every hand-written .ts under src/, with its path. `src/data` is generated by
 *  tonus-corpus and is not ours to hold to a comment rule. */
function sources(dir = join(ROOT, "src"), out = []) {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) {
      if (path.endsWith(join("src", "data"))) continue;
      sources(path, out);
    } else if (name.endsWith(".ts")) {
      out.push(path);
    }
  }
  return out;
}

const FILES = sources().map((path) => ({
  path,
  rel: path.slice(ROOT.length + 1),
  text: readFileSync(path, "utf8"),
}));

describe("comments — the reference pages moved to docs/api/", () => {
  // The whole reference moved under docs/api/ and eight comments went on
  // pointing at the old layout. Nothing failed: a path in a comment is prose,
  // and a reader following it just finds nothing. This is that class, caught
  // at the moment it is written rather than the day someone follows it.
  test("no comment points at a docs page outside docs/api/", () => {
    const stale = [];
    for (const { rel, text } of FILES) {
      for (const [i, line] of text.split("\n").entries()) {
        // A markdown page under docs/ that is NOT under docs/api/. The two
        // root-level documents that legitimately live there are excluded by
        // name rather than by pattern, so a new one has to be considered.
        const m = line.match(/docs\/(?!api\/)([a-z-]+\.md)/);
        if (m && !["index.md"].includes(m[1])) stale.push(`${rel}:${i + 1}  ${m[0]}`);
      }
    }
    assert.deepEqual(stale, [], `stale doc paths:\n  ${stale.join("\n  ")}`);
  });

  test("every docs/api page a comment names exists", () => {
    const missing = [];
    for (const { rel, text } of FILES) {
      for (const [i, line] of text.split("\n").entries()) {
        const m = line.match(/docs\/api\/([a-z-]+\.md)/);
        if (!m) continue;
        try {
          readFileSync(join(ROOT, "docs", "api", m[1]));
        } catch {
          missing.push(`${rel}:${i + 1}  ${m[0]}`);
        }
      }
    }
    assert.deepEqual(missing, [], `dangling doc paths:\n  ${missing.join("\n  ")}`);
  });
});

describe("comments — a path resolves from the file that names it", () => {
  // The docs/api move was only half the defect. Every path was ALSO written as
  // if from the repo root, from files three and four levels down, so none of
  // them resolved where it was written — an editor following `BIBLIOGRAPHY.md`
  // out of src/engines/chant/data/ looks for it in that directory. Checking
  // that a file exists somewhere is not the same as checking the link works.
  test("every repo path in a comment resolves relative to its own file", () => {
    const PATHISH =
      /(?:\.\.\/)*(?:docs|tests|scripts)\/[\w./-]*\.\w+|(?:\.\.\/)*BIBLIOGRAPHY\.md/g;
    const broken = [];
    for (const { path, rel, text } of FILES) {
      const here = dirname(path);
      for (const [i, line] of text.split("\n").entries()) {
        const trimmed = line.trim();
        const isComment = trimmed.startsWith("//") || trimmed.startsWith("*")
          || trimmed.startsWith("/*");
        if (!isComment) continue;
        for (const m of line.matchAll(PATHISH)) {
          // Trailing sentence punctuation is not part of the path.
          const target = m[0].replace(/[.,;:]+$/, "");
          try {
            statSync(resolve(here, target));
          } catch {
            broken.push(`${rel}:${i + 1}  ${target}`);
          }
        }
      }
    }
    assert.deepEqual(broken, [], `paths that do not resolve from their own file:`
      + `\n  ${broken.join("\n  ")}`);
  });
});

describe("comments — a constant restated in prose", () => {
  // census.ts's header gave the block width twice, and both said 225 against a
  // constant of 221. The number is load-bearing prose: it is how a reader
  // understands the layout the engine indexes into. So the comment has to
  // agree with the export.
  test("the census header quotes CENSUS_BLOCK_FLOATS", async () => {
    const { CENSUS_BLOCK_FLOATS } = await import("../dist/data/census.js");
    const header = FILES.find((f) => f.rel.endsWith(join("census", "census.ts")));
    assert.ok(header, "src/engines/census/census.ts not found");

    // Every bare 3-digit number in the file's opening comment block. The width
    // is the only one there, so anything that is not the constant is a stale
    // restatement of it.
    const block = header.text.slice(0, header.text.indexOf("\nimport"));
    const numbers = [...block.matchAll(/\b(\d{3})\b/g)].map((m) => Number(m[1]));
    const wrong = numbers.filter((n) => n !== CENSUS_BLOCK_FLOATS && n !== 121);
    assert.deepEqual(
      wrong, [],
      `census.ts's header quotes ${wrong.join(", ")} where the block is `
      + `${CENSUS_BLOCK_FLOATS} floats (121 is the melodic bigram, allowed)`,
    );
  });
});

describe("comments — every [biblio: key] resolves", () => {
  // The bibliography is the single source of truth for citations, and code
  // cites into it by bracketed key. A key that does not resolve is a citation
  // to nothing — the same failure as a dangling path, in the register the
  // project cares most about.
  test("no citation names a key BIBLIOGRAPHY.md does not carry", () => {
    const biblio = readFileSync(join(ROOT, "BIBLIOGRAPHY.md"), "utf8");
    // Entries are list items — `- \`key\` — **Title.**` — not headings. Match
    // that form directly: a fallback to "any text in backticks" would accept
    // almost anything and quietly stop testing.
    const keys = new Set(
      [...biblio.matchAll(/^\s*-\s+`([a-z0-9-]+)`\s+—/gm)].map((m) => m[1]),
    );
    assert.ok(keys.size > 20, `parsed only ${keys.size} keys from BIBLIOGRAPHY.md `
      + "— has the entry format changed?");

    const dangling = [];
    for (const { rel, text } of FILES) {
      for (const [i, line] of text.split("\n").entries()) {
        for (const m of line.matchAll(/\[biblio:\s*([a-z0-9-]+)\s*\]/g)) {
          if (!keys.has(m[1])) dangling.push(`${rel}:${i + 1}  ${m[1]}`);
        }
      }
    }
    assert.deepEqual(dangling, [], `unresolved citations:\n  ${dangling.join("\n  ")}`);
  });
});
