#!/usr/bin/env node
// ---------------------------------------------------------------------------
// vendor-ink.mjs — copy the compiled ink system into the site
// ---------------------------------------------------------------------------
// The design system has exactly one definition: src/engines/score/emitters/
// atramentum.ts, which the score's analysis tracks draw with. The site's
// diagrams must draw with the SAME one, or it stops being a design system --
// so the site does not keep a hand-written copy. This copies the compiled
// module to site/diagrams/ink.js with a generated header.
//
// Run it after `npm run build`; `npm run site` does both.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(HERE, "..", "dist", "engines", "score", "emitters", "atramentum.js");
const OUT = resolve(HERE, "..", "site", "diagrams", "ink.js");

const BANNER = `// AUTO-GENERATED by scripts/vendor-ink.mjs — do not edit.
// Source: src/engines/score/emitters/atramentum.ts (the one definition).
// Regenerate with \`npm run site\`.
`;

let src;
try {
  src = await readFile(SRC, "utf8");
} catch {
  console.error(`vendor-ink: ${SRC} not found — run \`npm run build\` first.`);
  process.exit(1);
}

// The compiled module is already dependency-free ESM; nothing to rewrite.
if (/^\s*import\s/m.test(src)) {
  console.error("vendor-ink: atramentum grew an import — the site copy assumes it has none.");
  process.exit(1);
}

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, BANNER + src);
console.log(`vendored the ink → site/diagrams/ink.js (${(src.length / 1024).toFixed(1)}KB)`);
