// AUTO-GENERATED by scripts/extract-attestation.mjs — do not edit manually
// When each chant is first WITNESSED, from CANTUS's manuscript index.
// 1963 chants dated.

import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

/** One chant's manuscript attestation. `century` is a TERMINUS ANTE QUEM:
 *  the chant existed by then because a book from that century holds it — it
 *  is NOT a composition date, and an undated chant may be older still. */
export interface Attestation {
  /** Earliest surviving witness, as a century number (10 = the 900s). */
  century: number;
  /** Latest witness, same scale — how long it stayed in use. */
  latest: number;
  /** How many indexed manuscript witnesses CANTUS holds. */
  witnesses: number;
  /** Which cursus transmits it, where CANTUS records one. */
  cursus: "monastic" | "secular" | "both" | null;
  /** The Cantus ID this attestation was read from. */
  cantusId: string;
  /** How the id was assigned: the direct text matcher, or the nocturnale crosswalk (gap-fill only). */
  via: "map" | "crosswalk";
}

const __dir = dirname(fileURLToPath(import.meta.url));
export const ATTESTATION: Record<string, Attestation> = (
  JSON.parse(readFileSync(resolve(__dir, "attestation.json"), "utf8")) as {
    byChant: Record<string, Attestation>;
  }
).byChant;
