// AUTO-GENERATED by scripts/bake-cadentiae.mjs — do not edit manually
// (No timestamp by design: identical input must bake to an identical file,
// or every regeneration churns the diff. Git carries the dates.)
// ---------------------------------------------------------------------------
// data/cadentiae — the corpus-grounded cadence catalogue (CADENTIAE)
// ---------------------------------------------------------------------------
// Every phrase-end in the corpus tonus SHIPS (am, ams, cot, cse, gr, ky, la, lh, lu, nr, psm — 28481
// ends), keyed by the last <=4 notes' interval signature in semitones (the
// shape — the gesture) and the closing note's offset from the CHANT'S OWN
// closing note (its sounded final — not the labeled mode's final), as a SIGNED
// semitone count (the arrival — the function).
//
// The arrival is deliberately not octave-reduced: the mod-12 fold pooled a
// fifth ABOVE the final with a fourth BELOW — measured, 3,499 of
// 27,985 phrase ends landed on @-5, of which 2,427 were really +7. Two
// opposite gestures under one key. Folding survives as a degree field on a live
// cadence event, where it is the scale degree and mode-theoretically real.
//
// The population is the SUNG corpus, not the printed books: this table and the
// census now count the same chants, which they never did before. No Latin
// arrival names ride the table, for the same reason no family names do:
// the key carries the arrival; the reader can count. Families with n >= 50 are tabled here (122 families,
// 58.7% of all phrase-ends); the full tally lives in the mining
// artifact. finality = share of a family's occurrences at a final close
// ("::" or chant end) — measured function, continuous, corpus-derived.
//
// This is inventa, not tradita: a computed catalogue with stated method and
// open code ("tonus catalogue, method §cadentiae"). Families are identified by
// their key alone — the shape and its arrival; no editorial names ride the
// table. Method + display doctrine: working/design-analysis-track.md §CADENTIAE.

/** One corpus cadence family: a (shape, arrival) pair with its statistics. */
export interface CadentiaFamilia {
  /** "shape @arrival", e.g. "2,0,-2 @0" — joins mining/census artifacts. */
  key: string;
  /** Interval signature in semitones between the tail's consecutive notes. */
  shape: number[];
  /** Closing note minus the chant's own closing note (sounded final),
   *  in SIGNED semitones — not octave-reduced; see the arrival note above. */
  arrival: number;
  /** Corpus occurrences. */
  n: number;
  /** `n` over ALL phrase-ends (CADENTIAE_POPULATION.ends) — not over the
   *  tabled subset, which would flatter every family that cleared the floor. */
  share: number;
  /** Share of occurrences at a final close — the measured finality index. */
  finality: number;
  /** Occurrences by mode digit ("1".."8"; "?" = mode-less chants). */
  modes: Record<string, number>;
}

/**
 * The denominator behind every `share`: all phrase-ends in the sung corpus,
 * and the same total per mode digit. Both are the FULL tally, never summed
 * from the tabled families — a family's mode counts divided by the tabled
 * subset would overstate every one of them.
 *
 * With `byMode`, a family's lift in a given mode is one division:
 * `(modes[m] / byMode[m]) / share` — how much more (or less) that mode
 * reaches for this close than the corpus at large. Baked as vocabulary, not
 * as arithmetic: the ratio is the caller's to take.
 */
export const CADENTIAE_POPULATION: {
  readonly ends: number;
  readonly byMode: Readonly<Record<string, number>>;
} = Object.freeze({
  ends: 28481,
  byMode: Object.freeze({"1":5497,"2":3866,"3":2699,"4":3155,"5":2925,"6":1682,"7":3423,"8":4954,"?":280}),
});

/** The cadence catalogue, most frequent family first. */
export const CADENTIAE: CadentiaFamilia[] = [
  {"key":"2,0,-2 @0","shape":[2,0,-2],"arrival":0,"n":1131,"share":0.0397,"finality":0.434,"modes":{"1":157,"2":206,"3":34,"4":8,"5":146,"6":146,"7":109,"8":323,"?":2}},
  {"key":"2,-2,0 @0","shape":[2,-2,0],"arrival":0,"n":838,"share":0.0294,"finality":0.408,"modes":{"1":84,"2":137,"3":7,"4":4,"5":104,"6":163,"7":108,"8":210,"?":21}},
  {"key":"-2,0,-2 @0","shape":[-2,0,-2],"arrival":0,"n":617,"share":0.0217,"finality":0.695,"modes":{"1":6,"2":24,"3":2,"4":2,"5":189,"6":33,"7":121,"8":239,"?":1}},
  {"key":"-2,2,0 @0","shape":[-2,2,0],"arrival":0,"n":614,"share":0.0216,"finality":0.459,"modes":{"1":141,"2":139,"3":8,"4":61,"7":62,"8":191,"?":12}},
  {"key":"1,-1,-2 @0","shape":[1,-1,-2],"arrival":0,"n":365,"share":0.0128,"finality":0.49,"modes":{"1":243,"2":93,"3":1,"4":8,"5":3,"7":8,"8":9}},
  {"key":"-2,2,-2 @0","shape":[-2,2,-2],"arrival":0,"n":351,"share":0.0123,"finality":0.305,"modes":{"1":33,"2":39,"3":11,"4":3,"5":22,"6":18,"7":50,"8":174,"?":1}},
  {"key":"2,0,-2 @-2","shape":[2,0,-2],"arrival":-2,"n":333,"share":0.0117,"finality":0.228,"modes":{"1":63,"2":51,"3":50,"4":13,"5":36,"6":6,"7":22,"8":74,"?":18}},
  {"key":"2,-2,-2 @0","shape":[2,-2,-2],"arrival":0,"n":304,"share":0.0107,"finality":0.48,"modes":{"1":27,"2":3,"3":7,"5":42,"6":45,"7":52,"8":127,"?":1}},
  {"key":"-2,0,-2 @-2","shape":[-2,0,-2],"arrival":-2,"n":270,"share":0.0095,"finality":0.067,"modes":{"1":79,"2":73,"3":1,"4":2,"5":2,"7":13,"8":100}},
  {"key":"-2,-1,0 @0","shape":[-2,-1,0],"arrival":0,"n":268,"share":0.0094,"finality":0.66,"modes":{"3":95,"4":169,"6":1,"?":3}},
  {"key":"2,2,-2 @0","shape":[2,2,-2],"arrival":0,"n":266,"share":0.0093,"finality":0.44,"modes":{"1":48,"2":128,"3":8,"4":2,"5":1,"6":6,"7":18,"8":55}},
  {"key":"2,0,-2 @3","shape":[2,0,-2],"arrival":3,"n":254,"share":0.0089,"finality":0.035,"modes":{"1":48,"2":53,"3":32,"4":53,"5":39,"6":3,"7":8,"8":12,"?":6}},
  {"key":"-2,-2,0 @0","shape":[-2,-2,0],"arrival":0,"n":253,"share":0.0089,"finality":0.545,"modes":{"1":4,"4":2,"5":29,"6":84,"7":32,"8":101,"?":1}},
  {"key":"-1,-2,0 @0","shape":[-1,-2,0],"arrival":0,"n":249,"share":0.0087,"finality":0.59,"modes":{"1":147,"2":80,"3":15,"7":1,"8":3,"?":3}},
  {"key":"-3,2,-2 @0","shape":[-3,2,-2],"arrival":0,"n":240,"share":0.0084,"finality":0.292,"modes":{"1":89,"2":113,"3":17,"4":14,"5":6,"7":1}},
  {"key":"-2,-2,2 @0","shape":[-2,-2,2],"arrival":0,"n":237,"share":0.0083,"finality":0.464,"modes":{"1":86,"2":74,"3":7,"4":4,"5":13,"7":13,"8":39,"?":1}},
  {"key":"0,-2,0 @0","shape":[0,-2,0],"arrival":0,"n":223,"share":0.0078,"finality":0.552,"modes":{"1":33,"2":16,"4":1,"5":1,"6":50,"7":14,"8":104,"?":4}},
  {"key":"2,-4,2 @0","shape":[2,-4,2],"arrival":0,"n":220,"share":0.0077,"finality":0.668,"modes":{"1":21,"2":14,"3":127,"4":3,"7":16,"8":38,"?":1}},
  {"key":"2,-2,-2 @-2","shape":[2,-2,-2],"arrival":-2,"n":216,"share":0.0076,"finality":0.12,"modes":{"1":59,"2":76,"3":7,"7":14,"8":58,"?":2}},
  {"key":"1,-3,0 @0","shape":[1,-3,0],"arrival":0,"n":213,"share":0.0075,"finality":0.333,"modes":{"1":124,"2":65,"3":1,"4":14,"5":8,"7":1}},
  {"key":"-2,2,-2 @-2","shape":[-2,2,-2],"arrival":-2,"n":212,"share":0.0074,"finality":0.123,"modes":{"1":22,"2":49,"3":11,"4":53,"5":1,"7":25,"8":45,"?":6}},
  {"key":"2,1,-3 @0","shape":[2,1,-3],"arrival":0,"n":195,"share":0.0068,"finality":0.938,"modes":{"1":67,"2":125,"3":2,"5":1}},
  {"key":"-2,-1,-2 @0","shape":[-2,-1,-2],"arrival":0,"n":183,"share":0.0064,"finality":0.339,"modes":{"1":135,"2":28,"5":1,"7":19}},
  {"key":"0,0,-1 @0","shape":[0,0,-1],"arrival":0,"n":167,"share":0.0059,"finality":0.629,"modes":{"2":2,"3":53,"4":103,"5":4,"6":1,"7":1,"8":3}},
  {"key":"2,-4,0 @0","shape":[2,-4,0],"arrival":0,"n":161,"share":0.0057,"finality":0.516,"modes":{"5":33,"6":61,"7":23,"8":44}},
  {"key":"-1,-2,-2 @0","shape":[-1,-2,-2],"arrival":0,"n":160,"share":0.0056,"finality":0.362,"modes":{"2":2,"3":1,"4":1,"5":19,"6":24,"7":14,"8":98,"?":1}},
  {"key":"2,0,-2 @-4","shape":[2,0,-2],"arrival":-4,"n":160,"share":0.0056,"finality":0.469,"modes":{"1":21,"2":5,"3":17,"4":8,"5":34,"6":14,"7":33,"8":21,"?":7}},
  {"key":"0,0,0 @3","shape":[0,0,0],"arrival":3,"n":153,"share":0.0054,"finality":0.392,"modes":{"1":16,"2":33,"3":101,"5":2,"6":1}},
  {"key":"2,0,-2 @5","shape":[2,0,-2],"arrival":5,"n":151,"share":0.0053,"finality":0.073,"modes":{"1":39,"2":41,"3":7,"4":12,"5":21,"6":2,"7":5,"8":23,"?":1}},
  {"key":"0,2,-2 @0","shape":[0,2,-2],"arrival":0,"n":151,"share":0.0053,"finality":0.192,"modes":{"1":14,"2":25,"3":3,"4":2,"5":14,"6":32,"7":9,"8":52}},
  {"key":"-4,2,0 @0","shape":[-4,2,0],"arrival":0,"n":147,"share":0.0052,"finality":0.293,"modes":{"1":69,"2":39,"4":1,"7":10,"8":28}},
  {"key":"-3,0,-2 @0","shape":[-3,0,-2],"arrival":0,"n":142,"share":0.005,"finality":0.07,"modes":{"1":4,"2":28,"4":2,"5":9,"7":8,"8":91}},
  {"key":"2,0,-2 @2","shape":[2,0,-2],"arrival":2,"n":138,"share":0.0048,"finality":0.297,"modes":{"1":9,"2":16,"3":14,"4":2,"5":14,"6":45,"7":13,"8":21,"?":4}},
  {"key":"-1,0,-2 @0","shape":[-1,0,-2],"arrival":0,"n":133,"share":0.0047,"finality":0.353,"modes":{"1":57,"2":40,"3":1,"4":1,"7":27,"8":7}},
  {"key":"2,0,-2 @7","shape":[2,0,-2],"arrival":7,"n":131,"share":0.0046,"finality":0.023,"modes":{"1":12,"3":1,"5":77,"7":38,"8":3}},
  {"key":"2,-2,-3 @0","shape":[2,-2,-3],"arrival":0,"n":128,"share":0.0045,"finality":0.633,"modes":{"1":26,"2":8,"3":15,"4":72,"5":3,"8":4}},
  {"key":"-2,0,-1 @0","shape":[-2,0,-1],"arrival":0,"n":127,"share":0.0045,"finality":0.669,"modes":{"2":1,"3":41,"4":73,"6":6,"7":4,"8":2}},
  {"key":"2,0,0 @0","shape":[2,0,0],"arrival":0,"n":124,"share":0.0044,"finality":0.532,"modes":{"1":22,"2":16,"3":2,"4":43,"8":41}},
  {"key":"2,0,-2 @-7","shape":[2,0,-2],"arrival":-7,"n":124,"share":0.0044,"finality":0.306,"modes":{"1":21,"2":14,"3":9,"4":4,"5":12,"6":3,"7":35,"8":26}},
  {"key":"2,1,-1 @4","shape":[2,1,-1],"arrival":4,"n":123,"share":0.0043,"finality":0.146,"modes":{"1":13,"2":1,"3":3,"4":4,"5":10,"6":51,"7":15,"8":26}},
  {"key":"-2,0,-3 @0","shape":[-2,0,-3],"arrival":0,"n":119,"share":0.0042,"finality":0.765,"modes":{"1":21,"2":10,"3":58,"4":20,"5":3,"8":7}},
  {"key":"2,1,-1 @0","shape":[2,1,-1],"arrival":0,"n":119,"share":0.0042,"finality":0.269,"modes":{"1":11,"2":7,"3":27,"4":59,"5":3,"6":2,"7":7,"8":3}},
  {"key":"0,0,0 @7","shape":[0,0,0],"arrival":7,"n":117,"share":0.0041,"finality":0.53,"modes":{"1":29,"3":2,"5":18,"7":68}},
  {"key":"2,-2,0 @7","shape":[2,-2,0],"arrival":7,"n":117,"share":0.0041,"finality":0,"modes":{"1":29,"5":45,"6":6,"7":35,"8":2}},
  {"key":"1,-3,-2 @0","shape":[1,-3,-2],"arrival":0,"n":116,"share":0.0041,"finality":0.543,"modes":{"5":11,"6":1,"7":21,"8":82,"?":1}},
  {"key":"-2,2,-2 @5","shape":[-2,2,-2],"arrival":5,"n":114,"share":0.004,"finality":0.079,"modes":{"1":35,"2":2,"3":3,"4":17,"7":7,"8":50}},
  {"key":"-5,0,-2 @-2","shape":[-5,0,-2],"arrival":-2,"n":114,"share":0.004,"finality":0.035,"modes":{"1":28,"2":31,"3":7,"7":6,"8":42}},
  {"key":"2,-2,0 @3","shape":[2,-2,0],"arrival":3,"n":112,"share":0.0039,"finality":0,"modes":{"1":37,"2":46,"3":6,"4":15,"5":3,"6":2,"7":1,"8":1,"?":1}},
  {"key":"-3,0,-2 @-2","shape":[-3,0,-2],"arrival":-2,"n":106,"share":0.0037,"finality":0,"modes":{"1":40,"2":35,"3":8,"4":2,"5":3,"7":3,"8":15}},
  {"key":"2,-2,0 @5","shape":[2,-2,0],"arrival":5,"n":104,"share":0.0037,"finality":0.038,"modes":{"1":13,"2":20,"3":3,"4":13,"5":2,"6":3,"7":20,"8":27,"?":3}},
  {"key":"-2,0,-2 @3","shape":[-2,0,-2],"arrival":3,"n":103,"share":0.0036,"finality":0.019,"modes":{"1":32,"2":7,"3":52,"5":2,"6":1,"7":2,"8":7}},
  {"key":"2,-2,-2 @3","shape":[2,-2,-2],"arrival":3,"n":101,"share":0.0035,"finality":0.158,"modes":{"1":39,"2":36,"3":17,"4":7,"5":1,"8":1}},
  {"key":"0,-3,-2 @0","shape":[0,-3,-2],"arrival":0,"n":101,"share":0.0035,"finality":0.842,"modes":{"5":2,"6":2,"7":94,"8":3}},
  {"key":"-2,2,0 @7","shape":[-2,2,0],"arrival":7,"n":99,"share":0.0035,"finality":0.081,"modes":{"1":27,"2":3,"3":2,"5":1,"7":60,"8":5,"?":1}},
  {"key":"2,2,0 @7","shape":[2,2,0],"arrival":7,"n":99,"share":0.0035,"finality":0.071,"modes":{"1":64,"2":17,"3":10,"8":1,"?":7}},
  {"key":"-2,2,-2 @3","shape":[-2,2,-2],"arrival":3,"n":98,"share":0.0034,"finality":0.082,"modes":{"1":21,"2":30,"3":17,"4":13,"5":2,"7":8,"8":7}},
  {"key":"2,0,-2 @-5","shape":[2,0,-2],"arrival":-5,"n":97,"share":0.0034,"finality":0.258,"modes":{"1":11,"2":8,"3":3,"4":4,"5":6,"6":14,"7":20,"8":31}},
  {"key":"-2,-2,0 @-2","shape":[-2,-2,0],"arrival":-2,"n":92,"share":0.0032,"finality":0.087,"modes":{"1":16,"2":24,"3":4,"4":1,"5":1,"6":8,"7":4,"8":33,"?":1}},
  {"key":"0,0,-3 @0","shape":[0,0,-3],"arrival":0,"n":90,"share":0.0032,"finality":0.556,"modes":{"1":50,"2":34,"3":2,"4":3,"5":1}},
  {"key":"4,0,-2 @0","shape":[4,0,-2],"arrival":0,"n":88,"share":0.0031,"finality":0.648,"modes":{"1":29,"2":24,"7":22,"8":13}},
  {"key":"2,-2,-2 @-4","shape":[2,-2,-2],"arrival":-4,"n":88,"share":0.0031,"finality":0.409,"modes":{"1":21,"2":2,"3":1,"4":29,"5":3,"6":14,"7":2,"8":2,"?":14}},
  {"key":"-2,0,-2 @-5","shape":[-2,0,-2],"arrival":-5,"n":87,"share":0.0031,"finality":0.207,"modes":{"1":6,"2":23,"3":1,"5":25,"6":5,"8":27}},
  {"key":"0,0,0 @5","shape":[0,0,0],"arrival":5,"n":86,"share":0.003,"finality":0.209,"modes":{"2":8,"4":36,"5":5,"7":2,"8":35}},
  {"key":"1,0,-1 @0","shape":[1,0,-1],"arrival":0,"n":86,"share":0.003,"finality":0.267,"modes":{"1":6,"3":5,"4":45,"5":20,"6":1,"7":9}},
  {"key":"2,1,-1 @7","shape":[2,1,-1],"arrival":7,"n":86,"share":0.003,"finality":0,"modes":{"1":54,"2":7,"3":21,"4":3,"8":1}},
  {"key":"2,2,-2 @2","shape":[2,2,-2],"arrival":2,"n":84,"share":0.0029,"finality":0,"modes":{"1":10,"4":2,"5":14,"6":8,"7":12,"8":38}},
  {"key":"3,2,-2 @0","shape":[3,2,-2],"arrival":0,"n":80,"share":0.0028,"finality":0.637,"modes":{"1":3,"4":6,"5":10,"6":49,"7":2,"8":10}},
  {"key":"3,0,0 @3","shape":[3,0,0],"arrival":3,"n":79,"share":0.0028,"finality":0.165,"modes":{"1":2,"3":63,"5":13,"7":1}},
  {"key":"0,2,-2 @7","shape":[0,2,-2],"arrival":7,"n":79,"share":0.0028,"finality":0,"modes":{"1":11,"3":1,"5":55,"7":10,"8":2}},
  {"key":"4,-2,0 @0","shape":[4,-2,0],"arrival":0,"n":79,"share":0.0028,"finality":0.253,"modes":{"1":12,"2":30,"6":2,"7":9,"8":26}},
  {"key":"-2,0,-2 @-4","shape":[-2,0,-2],"arrival":-4,"n":79,"share":0.0028,"finality":0.177,"modes":{"2":23,"3":7,"4":16,"5":7,"6":9,"7":3,"8":14}},
  {"key":"2,2,-2 @7","shape":[2,2,-2],"arrival":7,"n":79,"share":0.0028,"finality":0.013,"modes":{"1":1,"2":2,"5":7,"6":1,"7":62,"8":5,"?":1}},
  {"key":"-1,-2,-2 @-2","shape":[-1,-2,-2],"arrival":-2,"n":79,"share":0.0028,"finality":0.025,"modes":{"1":33,"2":41,"3":2,"6":2,"7":1}},
  {"key":"-2,2,0 @2","shape":[-2,2,0],"arrival":2,"n":78,"share":0.0027,"finality":0,"modes":{"1":6,"2":41,"5":4,"6":4,"7":19,"8":4}},
  {"key":"2,2,0 @2","shape":[2,2,0],"arrival":2,"n":76,"share":0.0027,"finality":0.026,"modes":{"1":24,"2":15,"3":7,"7":5,"8":25}},
  {"key":"-4,2,-2 @0","shape":[-4,2,-2],"arrival":0,"n":75,"share":0.0026,"finality":0.547,"modes":{"3":1,"5":55,"6":6,"7":9,"8":4}},
  {"key":"-2,2,-2 @2","shape":[-2,2,-2],"arrival":2,"n":75,"share":0.0026,"finality":0.16,"modes":{"1":8,"2":3,"3":4,"4":2,"5":10,"6":21,"7":13,"8":14}},
  {"key":"1,2,0 @0","shape":[1,2,0],"arrival":0,"n":74,"share":0.0026,"finality":0.649,"modes":{"7":4,"8":70}},
  {"key":"1,0,-1 @2","shape":[1,0,-1],"arrival":2,"n":73,"share":0.0026,"finality":0.082,"modes":{"1":7,"2":43,"3":8,"4":3,"5":8,"7":3,"8":1}},
  {"key":"2,-4,0 @-2","shape":[2,-4,0],"arrival":-2,"n":73,"share":0.0026,"finality":0.082,"modes":{"1":2,"2":29,"3":1,"4":2,"5":2,"7":15,"8":22}},
  {"key":"-2,2,-2 @-5","shape":[-2,2,-2],"arrival":-5,"n":73,"share":0.0026,"finality":0.329,"modes":{"1":1,"2":5,"3":2,"4":10,"5":2,"6":7,"7":11,"8":35}},
  {"key":"-2,-3,0 @0","shape":[-2,-3,0],"arrival":0,"n":72,"share":0.0025,"finality":0.208,"modes":{"1":12,"2":35,"3":3,"4":16,"5":6}},
  {"key":"1,-1,-2 @-2","shape":[1,-1,-2],"arrival":-2,"n":72,"share":0.0025,"finality":0.264,"modes":{"1":4,"2":4,"3":12,"4":48,"7":1,"8":3}},
  {"key":"3,-1,-2 @0","shape":[3,-1,-2],"arrival":0,"n":71,"share":0.0025,"finality":0.296,"modes":{"1":32,"2":25,"3":8,"7":1,"8":2,"?":3}},
  {"key":"-1,-4,2 @0","shape":[-1,-4,2],"arrival":0,"n":71,"share":0.0025,"finality":0.352,"modes":{"1":53,"2":16,"4":1,"7":1}},
  {"key":"3,-1,-4 @0","shape":[3,-1,-4],"arrival":0,"n":70,"share":0.0025,"finality":0.786,"modes":{"5":59,"8":11}},
  {"key":"-1,1,-1 @0","shape":[-1,1,-1],"arrival":0,"n":69,"share":0.0024,"finality":0.87,"modes":{"1":6,"2":5,"3":2,"4":6,"5":4,"6":1,"7":29,"8":7,"?":9}},
  {"key":"1,-3,-2 @-2","shape":[1,-3,-2],"arrival":-2,"n":68,"share":0.0024,"finality":0,"modes":{"1":9,"2":29,"8":30}},
  {"key":"-1,1,-1 @4","shape":[-1,1,-1],"arrival":4,"n":68,"share":0.0024,"finality":0.221,"modes":{"1":5,"4":2,"5":7,"7":52,"8":2}},
  {"key":"-3,1,-3 @0","shape":[-3,1,-3],"arrival":0,"n":68,"share":0.0024,"finality":0.456,"modes":{"1":32,"2":7,"5":29}},
  {"key":"2,2,-2 @5","shape":[2,2,-2],"arrival":5,"n":68,"share":0.0024,"finality":0.015,"modes":{"1":29,"2":4,"3":4,"4":25,"5":1,"7":5}},
  {"key":"-3,0,-2 @3","shape":[-3,0,-2],"arrival":3,"n":66,"share":0.0023,"finality":0.015,"modes":{"1":14,"2":17,"3":27,"4":5,"7":1,"8":2}},
  {"key":"1,-1,-2 @-5","shape":[1,-1,-2],"arrival":-5,"n":66,"share":0.0023,"finality":0.212,"modes":{"1":15,"2":2,"3":1,"4":6,"7":5,"8":37}},
  {"key":"2,-2,0 @2","shape":[2,-2,0],"arrival":2,"n":65,"share":0.0023,"finality":0.062,"modes":{"1":4,"2":3,"5":10,"6":21,"7":11,"8":15,"?":1}},
  {"key":"-1,1,-3 @0","shape":[-1,1,-3],"arrival":0,"n":64,"share":0.0022,"finality":0.281,"modes":{"1":34,"2":21,"3":6,"5":1,"8":2}},
  {"key":"-2,-1,-2 @-2","shape":[-2,-1,-2],"arrival":-2,"n":64,"share":0.0022,"finality":0.203,"modes":{"3":28,"4":36}},
  {"key":"-3,2,-2 @-2","shape":[-3,2,-2],"arrival":-2,"n":64,"share":0.0022,"finality":0,"modes":{"3":40,"4":24}},
  {"key":"0,2,0 @0","shape":[0,2,0],"arrival":0,"n":64,"share":0.0022,"finality":0.281,"modes":{"1":16,"2":6,"3":2,"4":17,"6":4,"8":15,"?":4}},
  {"key":"2,-2,-1 @0","shape":[2,-2,-1],"arrival":0,"n":63,"share":0.0022,"finality":0.381,"modes":{"1":1,"3":7,"4":49,"5":3,"7":3}},
  {"key":"0,-1,-2 @0","shape":[0,-1,-2],"arrival":0,"n":62,"share":0.0022,"finality":0.371,"modes":{"1":16,"2":22,"3":4,"4":13,"5":6,"8":1}},
  {"key":"-2,-2,0 @3","shape":[-2,-2,0],"arrival":3,"n":60,"share":0.0021,"finality":0,"modes":{"1":18,"2":15,"3":15,"4":9,"5":1,"7":1,"8":1}},
  {"key":" @0","shape":[],"arrival":0,"n":60,"share":0.0021,"finality":1,"modes":{"1":12,"2":4,"3":6,"4":4,"5":5,"6":4,"7":15,"8":10}},
  {"key":"0,0,-1 @-5","shape":[0,0,-1],"arrival":-5,"n":59,"share":0.0021,"finality":0.712,"modes":{"3":45,"4":14}},
  {"key":"-2,2,-2 @7","shape":[-2,2,-2],"arrival":7,"n":58,"share":0.002,"finality":0.069,"modes":{"1":8,"5":14,"7":35,"8":1}},
  {"key":"-2,-1,0 @-5","shape":[-2,-1,0],"arrival":-5,"n":58,"share":0.002,"finality":1,"modes":{"3":57,"4":1}},
  {"key":"-1,1,2 @5","shape":[-1,1,2],"arrival":5,"n":57,"share":0.002,"finality":0.018,"modes":{"1":25,"2":31,"5":1}},
  {"key":"-2,2,-5 @-5","shape":[-2,2,-5],"arrival":-5,"n":57,"share":0.002,"finality":0,"modes":{"1":11,"2":22,"3":6,"4":9,"8":9}},
  {"key":"2,-2,0 @-2","shape":[2,-2,0],"arrival":-2,"n":57,"share":0.002,"finality":0.105,"modes":{"1":5,"2":7,"3":3,"4":3,"5":7,"6":2,"7":5,"8":21,"?":4}},
  {"key":"-5,0,-2 @0","shape":[-5,0,-2],"arrival":0,"n":56,"share":0.002,"finality":0.054,"modes":{"4":1,"5":15,"6":2,"7":32,"8":6}},
  {"key":"0,0,-3 @4","shape":[0,0,-3],"arrival":4,"n":55,"share":0.0019,"finality":0,"modes":{"5":55}},
  {"key":"-2,0,-3 @4","shape":[-2,0,-3],"arrival":4,"n":55,"share":0.0019,"finality":0,"modes":{"5":42,"6":1,"7":10,"8":2}},
  {"key":"-3,-2,2 @0","shape":[-3,-2,2],"arrival":0,"n":55,"share":0.0019,"finality":0.255,"modes":{"1":3,"2":33,"3":2,"4":2,"5":1,"7":1,"8":12,"?":1}},
  {"key":"0,-2,2 @0","shape":[0,-2,2],"arrival":0,"n":55,"share":0.0019,"finality":0.145,"modes":{"1":5,"2":10,"3":6,"8":34}},
  {"key":"-3,2,-2 @4","shape":[-3,2,-2],"arrival":4,"n":54,"share":0.0019,"finality":0,"modes":{"1":1,"5":53}},
  {"key":"1,0,-1 @4","shape":[1,0,-1],"arrival":4,"n":54,"share":0.0019,"finality":0.167,"modes":{"1":4,"5":22,"6":7,"7":16,"8":5}},
  {"key":"0,2,-2 @3","shape":[0,2,-2],"arrival":3,"n":54,"share":0.0019,"finality":0,"modes":{"1":10,"2":10,"3":1,"4":15,"5":7,"7":7,"8":4}},
  {"key":"-2,-2,-1 @0","shape":[-2,-2,-1],"arrival":0,"n":54,"share":0.0019,"finality":0.556,"modes":{"3":2,"4":52}},
  {"key":"2,2,0 @0","shape":[2,2,0],"arrival":0,"n":52,"share":0.0018,"finality":0.462,"modes":{"1":13,"2":2,"3":1,"4":29,"5":1,"6":1,"7":1,"8":1,"?":3}},
  {"key":"-2,2,0 @5","shape":[-2,2,0],"arrival":5,"n":51,"share":0.0018,"finality":0,"modes":{"1":7,"2":6,"3":4,"4":26,"?":8}},
  {"key":"-2,0,2 @9","shape":[-2,0,2],"arrival":9,"n":50,"share":0.0018,"finality":0,"modes":{"7":50}},
  {"key":"2,-2,-3 @-3","shape":[2,-2,-3],"arrival":-3,"n":50,"share":0.0018,"finality":0.14,"modes":{"1":2,"4":2,"5":19,"6":27}},
  {"key":"1,-1,-2 @7","shape":[1,-1,-2],"arrival":7,"n":50,"share":0.0018,"finality":0.02,"modes":{"1":21,"7":26,"8":3}},
];
