// AUTO-GENERATED by scripts/bake-cadentiae.mjs — do not edit manually
// Generated: 2026-07-20T15:03:55.912Z
// ---------------------------------------------------------------------------
// data/cadentiae — the corpus-grounded cadence catalogue (CADENTIAE)
// ---------------------------------------------------------------------------
// Every phrase-end in the corpus (gr, lu, la, lh, am, nr, ky — 77275
// ends from the full retrievable repertory), keyed by the last <=4 notes'
// interval signature in semitones (the shape — the gesture) and the closing
// note's offset from the chant final, octave-reduced to [-5..+6] (the arrival —
// the function). Families with n >= 150 are tabled here (117 families,
// 61.1% of all phrase-ends); the full tally lives in the mining
// artifact. finality = share of a family's occurrences at a final close
// ("::" or chant end) — measured function, continuous, corpus-derived.
//
// This is inventa, not tradita: a computed catalogue with stated method and
// open code ("tonus catalogue, method §cadentiae"). The shape binomials are
// DRAFTS pending the editorial naming pass; unnamed families carry null.
// Method + display doctrine: working/design-analysis-track.md §CADENTIAE.

/** One corpus cadence family: a (shape, arrival) pair with its statistics. */
export interface CadentiaFamilia {
  /** "shape @arrival", e.g. "2,0,-2 @0" — joins mining/census artifacts. */
  key: string;
  /** Draft Latin binomial for the shape (the gesture), or null if unnamed. */
  familia: string | null;
  /** Interval signature in semitones between the tail's consecutive notes. */
  shape: number[];
  /** Closing note minus chant final, semitones, octave-reduced to [-5..+6]. */
  arrival: number;
  /** The arrival case, mode-independent: "in finalem", "in tertiam", ... */
  adventus: string;
  /** Corpus occurrences. */
  n: number;
  /** Share of occurrences at a final close — the measured finality index. */
  finality: number;
  /** Occurrences by mode digit ("1".."8"; "?" = mode-less chants). */
  modes: Record<string, number>;
}

/** The cadence catalogue, most frequent family first. */
export const CADENTIAE: CadentiaFamilia[] = [
  {"key":"2,0,-2 @0","familia":"circuitus supra","shape":[2,0,-2],"arrival":0,"adventus":"in finalem","n":2861,"finality":0.439,"modes":{"1":286,"2":635,"3":74,"4":56,"5":246,"6":362,"7":197,"8":961,"62":12,"?":32}},
  {"key":"-2,2,0 @0","familia":"circuitus infra","shape":[-2,2,0],"arrival":0,"adventus":"in finalem","n":2257,"finality":0.45,"modes":{"1":428,"2":522,"3":34,"4":365,"5":1,"7":116,"8":713,"32":8,"?":70}},
  {"key":"2,-2,0 @0","familia":"tactus supra","shape":[2,-2,0],"arrival":0,"adventus":"in finalem","n":1516,"finality":0.387,"modes":{"1":143,"2":208,"3":14,"4":43,"5":155,"6":250,"7":171,"8":441,"62":1,"?":90}},
  {"key":"-2,-2,2 @0","familia":"descensus simplex","shape":[-2,-2,2],"arrival":0,"adventus":"in finalem","n":1197,"finality":0.631,"modes":{"1":311,"2":424,"3":15,"4":13,"5":18,"6":1,"7":27,"8":346,"32":5,"33":3,"?":34}},
  {"key":"-1,-2,0 @0","familia":"descensus per semitonium","shape":[-1,-2,0],"arrival":0,"adventus":"in finalem","n":1136,"finality":0.64,"modes":{"1":883,"2":190,"3":21,"6":8,"7":9,"8":8,"?":17}},
  {"key":"-2,-2,0 @0","familia":"descensus simplex","shape":[-2,-2,0],"arrival":0,"adventus":"in finalem","n":1132,"finality":0.588,"modes":{"1":18,"2":3,"3":1,"4":5,"5":79,"6":262,"7":192,"8":563,"72":6,"?":3}},
  {"key":"-2,0,-2 @0","familia":"descensus repercussus","shape":[-2,0,-2],"arrival":0,"adventus":"in finalem","n":1091,"finality":0.693,"modes":{"1":18,"2":43,"3":8,"4":3,"5":249,"6":95,"7":177,"8":473,"63":2,"?":23}},
  {"key":"-2,2,-2 @0","familia":"flexus","shape":[-2,2,-2],"arrival":0,"adventus":"in finalem","n":1061,"finality":0.27,"modes":{"1":79,"2":166,"3":19,"4":30,"5":47,"6":61,"7":147,"8":495,"72":7,"82":2,"?":8}},
  {"key":"0,-2,0 @0","familia":null,"shape":[0,-2,0],"arrival":0,"adventus":"in finalem","n":1000,"finality":0.653,"modes":{"1":100,"2":78,"3":2,"4":3,"5":15,"6":165,"7":80,"8":499,"63":4,"82":1,"?":53}},
  {"key":"-2,-1,0 @0","familia":"descensus per semitonium","shape":[-2,-1,0],"arrival":0,"adventus":"in finalem","n":988,"finality":0.715,"modes":{"2":3,"3":486,"4":459,"5":2,"6":1,"7":6,"8":4,"32":3,"42":5,"?":19}},
  {"key":"2,-2,-2 @-2","familia":null,"shape":[2,-2,-2],"arrival":-2,"adventus":"in subfinalem","n":827,"finality":0.051,"modes":{"1":164,"2":279,"3":19,"7":39,"8":319,"?":7}},
  {"key":"2,-2,-2 @0","familia":null,"shape":[2,-2,-2],"arrival":0,"adventus":"in finalem","n":822,"finality":0.574,"modes":{"1":135,"2":8,"3":24,"4":1,"5":60,"6":136,"7":88,"8":356,"82":1,"?":13}},
  {"key":"2,0,-2 @-2","familia":"circuitus supra","shape":[2,0,-2],"arrival":-2,"adventus":"in subfinalem","n":811,"finality":0.276,"modes":{"1":144,"2":111,"3":93,"4":25,"5":61,"6":39,"7":50,"8":167,"?":121}},
  {"key":"2,2,-2 @0","familia":null,"shape":[2,2,-2],"arrival":0,"adventus":"in finalem","n":785,"finality":0.394,"modes":{"1":155,"2":274,"3":15,"4":8,"5":4,"6":16,"7":38,"8":268,"?":7}},
  {"key":"-2,-1,-2 @0","familia":"descensus per semitonium","shape":[-2,-1,-2],"arrival":0,"adventus":"in finalem","n":751,"finality":0.394,"modes":{"1":504,"2":137,"4":3,"5":3,"7":93,"8":1,"32":1,"?":9}},
  {"key":"1,-1,-2 @0","familia":"semitonium circumactum","shape":[1,-1,-2],"arrival":0,"adventus":"in finalem","n":714,"finality":0.41,"modes":{"1":453,"2":202,"3":1,"4":12,"5":8,"6":3,"7":18,"8":17}},
  {"key":"2,0,-2 @3","familia":"circuitus supra","shape":[2,0,-2],"arrival":3,"adventus":"in tertiam","n":707,"finality":0.035,"modes":{"1":77,"2":257,"3":68,"4":133,"5":79,"6":9,"7":31,"8":29,"42":9,"?":15}},
  {"key":"2,0,0 @0","familia":null,"shape":[2,0,0],"arrival":0,"adventus":"in finalem","n":695,"finality":0.414,"modes":{"1":104,"2":58,"3":42,"4":281,"7":17,"8":176,"32":3,"?":14}},
  {"key":"-2,0,-2 @-2","familia":"descensus repercussus","shape":[-2,0,-2],"arrival":-2,"adventus":"in subfinalem","n":677,"finality":0.081,"modes":{"1":246,"2":214,"3":8,"4":2,"5":4,"6":5,"7":25,"8":171,"?":2}},
  {"key":"-2,2,-2 @-2","familia":"flexus","shape":[-2,2,-2],"arrival":-2,"adventus":"in subfinalem","n":591,"finality":0.088,"modes":{"1":49,"2":79,"3":19,"4":261,"5":4,"6":9,"7":39,"8":94,"?":37}},
  {"key":"2,-2,-1 @0","familia":null,"shape":[2,-2,-1],"arrival":0,"adventus":"in finalem","n":572,"finality":0.561,"modes":{"1":3,"3":50,"4":478,"5":4,"7":3,"32":1,"?":33}},
  {"key":"2,0,-2 @5","familia":"circuitus supra","shape":[2,0,-2],"arrival":5,"adventus":"in quartam","n":561,"finality":0.168,"modes":{"1":88,"2":97,"3":26,"4":37,"5":85,"6":10,"7":106,"8":110,"?":2}},
  {"key":"-1,-2,-2 @0","familia":null,"shape":[-1,-2,-2],"arrival":0,"adventus":"in finalem","n":535,"finality":0.224,"modes":{"2":2,"3":4,"4":2,"5":54,"6":46,"7":63,"8":363,"?":1}},
  {"key":"2,-4,2 @0","familia":"ascensus deuteri","shape":[2,-4,2],"arrival":0,"adventus":"in finalem","n":531,"finality":0.54,"modes":{"1":35,"2":68,"3":185,"4":5,"7":22,"8":214,"42":1,"?":1}},
  {"key":"0,2,-2 @0","familia":null,"shape":[0,2,-2],"arrival":0,"adventus":"in finalem","n":524,"finality":0.174,"modes":{"1":40,"2":50,"3":7,"4":46,"5":22,"6":96,"7":20,"8":217,"12":1,"62":4,"?":21}},
  {"key":"-5,0,-2 @-2","familia":"lapsus quartae","shape":[-5,0,-2],"arrival":-2,"adventus":"in subfinalem","n":510,"finality":0.008,"modes":{"1":40,"2":258,"3":9,"7":6,"8":197}},
  {"key":"1,-3,0 @0","familia":null,"shape":[1,-3,0],"arrival":0,"adventus":"in finalem","n":505,"finality":0.448,"modes":{"1":315,"2":154,"3":2,"4":14,"5":14,"7":2,"8":2,"?":2}},
  {"key":"2,0,-2 @-5","familia":"circuitus supra","shape":[2,0,-2],"arrival":-5,"adventus":"in subquartam","n":448,"finality":0.156,"modes":{"1":52,"2":26,"3":16,"4":6,"5":126,"6":25,"7":121,"8":73,"62":3}},
  {"key":"-2,-2,0 @3","familia":"descensus simplex","shape":[-2,-2,0],"arrival":3,"adventus":"in tertiam","n":442,"finality":0.147,"modes":{"1":75,"2":47,"3":196,"4":60,"5":13,"7":14,"8":1,"12":1,"?":35}},
  {"key":"2,2,0 @-5","familia":null,"shape":[2,2,0],"arrival":-5,"adventus":"in subquartam","n":440,"finality":0.016,"modes":{"1":303,"2":90,"3":19,"4":2,"7":1,"8":3,"?":22}},
  {"key":"-1,-2,2 @0","familia":null,"shape":[-1,-2,2],"arrival":0,"adventus":"in finalem","n":437,"finality":0.796,"modes":{"2":6,"3":106,"4":318,"7":1,"8":2,"?":4}},
  {"key":"-3,2,-2 @0","familia":null,"shape":[-3,2,-2],"arrival":0,"adventus":"in finalem","n":435,"finality":0.255,"modes":{"1":129,"2":237,"3":24,"4":19,"5":24,"7":1,"33":1}},
  {"key":"2,-4,0 @0","familia":null,"shape":[2,-4,0],"arrival":0,"adventus":"in finalem","n":414,"finality":0.539,"modes":{"3":2,"5":65,"6":165,"7":58,"8":122,"82":1,"?":1}},
  {"key":"1,-3,-2 @0","familia":null,"shape":[1,-3,-2],"arrival":0,"adventus":"in finalem","n":402,"finality":0.714,"modes":{"1":1,"5":22,"6":3,"7":25,"8":348,"?":3}},
  {"key":"-2,2,-2 @5","familia":"flexus","shape":[-2,2,-2],"arrival":5,"adventus":"in quartam","n":389,"finality":0.09,"modes":{"1":92,"2":26,"3":46,"4":36,"5":15,"6":7,"7":56,"8":108,"?":3}},
  {"key":"2,-2,0 @5","familia":"tactus supra","shape":[2,-2,0],"arrival":5,"adventus":"in quartam","n":383,"finality":0.081,"modes":{"1":131,"2":26,"3":28,"4":30,"5":17,"6":20,"7":54,"8":66,"12":1,"?":10}},
  {"key":"-2,-2,0 @-2","familia":"descensus simplex","shape":[-2,-2,0],"arrival":-2,"adventus":"in subfinalem","n":380,"finality":0.132,"modes":{"1":90,"2":82,"3":13,"4":2,"5":16,"6":8,"7":38,"8":114,"32":4,"33":1,"?":12}},
  {"key":"-2,2,0 @-5","familia":"circuitus infra","shape":[-2,2,0],"arrival":-5,"adventus":"in subquartam","n":366,"finality":0.126,"modes":{"1":144,"2":3,"3":25,"4":8,"5":6,"7":145,"8":29,"33":1,"72":2,"?":3}},
  {"key":"-3,0,-2 @0","familia":null,"shape":[-3,0,-2],"arrival":0,"adventus":"in finalem","n":362,"finality":0.157,"modes":{"1":10,"2":43,"4":2,"5":12,"6":21,"7":31,"8":237,"62":6}},
  {"key":"2,0,-2 @2","familia":"circuitus supra","shape":[2,0,-2],"arrival":2,"adventus":"in secundam","n":340,"finality":0.294,"modes":{"1":22,"2":41,"3":21,"4":9,"5":24,"6":115,"7":32,"8":49,"?":27}},
  {"key":"2,0,-2 @-4","familia":"circuitus supra","shape":[2,0,-2],"arrival":-4,"adventus":"in subtertiam","n":330,"finality":0.597,"modes":{"1":30,"2":15,"3":29,"4":11,"5":75,"6":35,"7":50,"8":38,"?":47}},
  {"key":"-2,-2,2 @5","familia":"descensus simplex","shape":[-2,-2,2],"arrival":5,"adventus":"in quartam","n":329,"finality":0,"modes":{"1":41,"2":38,"3":44,"4":195,"5":1,"6":1,"?":9}},
  {"key":"3,-1,-2 @0","familia":null,"shape":[3,-1,-2],"arrival":0,"adventus":"in finalem","n":324,"finality":0.54,"modes":{"1":191,"2":78,"3":37,"7":1,"8":3,"?":14}},
  {"key":"2,1,-3 @0","familia":"elevata protica","shape":[2,1,-3],"arrival":0,"adventus":"in finalem","n":318,"finality":0.909,"modes":{"1":104,"2":211,"3":2,"5":1}},
  {"key":"2,2,-2 @-5","familia":null,"shape":[2,2,-2],"arrival":-5,"adventus":"in subquartam","n":303,"finality":0.017,"modes":{"1":18,"2":10,"3":4,"4":4,"5":8,"6":3,"7":199,"8":54,"?":3}},
  {"key":"1,2,0 @0","familia":null,"shape":[1,2,0],"arrival":0,"adventus":"in finalem","n":302,"finality":0.414,"modes":{"3":1,"7":15,"8":286}},
  {"key":"2,-2,0 @-5","familia":"tactus supra","shape":[2,-2,0],"arrival":-5,"adventus":"in subquartam","n":300,"finality":0.03,"modes":{"1":100,"2":3,"3":2,"5":61,"6":12,"7":102,"8":19,"72":1}},
  {"key":"-2,0,-2 @3","familia":"descensus repercussus","shape":[-2,0,-2],"arrival":3,"adventus":"in tertiam","n":294,"finality":0.116,"modes":{"1":96,"2":16,"3":115,"4":3,"5":8,"6":4,"7":30,"8":22}},
  {"key":"-1,0,-2 @0","familia":null,"shape":[-1,0,-2],"arrival":0,"adventus":"in finalem","n":294,"finality":0.296,"modes":{"1":106,"2":97,"3":1,"4":16,"7":59,"8":15}},
  {"key":"-4,2,0 @0","familia":null,"shape":[-4,2,0],"arrival":0,"adventus":"in finalem","n":289,"finality":0.27,"modes":{"1":103,"2":67,"3":2,"4":4,"7":15,"8":98}},
  {"key":"2,-2,-3 @0","familia":null,"shape":[2,-2,-3],"arrival":0,"adventus":"in finalem","n":286,"finality":0.441,"modes":{"1":89,"2":61,"3":24,"4":95,"5":9,"7":1,"8":6,"12":1}},
  {"key":"2,-2,-2 @3","familia":null,"shape":[2,-2,-2],"arrival":3,"adventus":"in tertiam","n":279,"finality":0.197,"modes":{"1":99,"2":73,"3":78,"4":20,"5":1,"7":1,"8":6,"13":1}},
  {"key":"2,1,-1 @4","familia":null,"shape":[2,1,-1],"arrival":4,"adventus":"in tertiam","n":278,"finality":0.133,"modes":{"1":23,"2":1,"3":6,"4":5,"5":19,"6":110,"7":22,"8":91,"?":1}},
  {"key":"2,1,-1 @0","familia":null,"shape":[2,1,-1],"arrival":0,"adventus":"in finalem","n":278,"finality":0.162,"modes":{"1":22,"2":11,"3":106,"4":112,"5":3,"6":4,"7":10,"8":8,"12":1,"?":1}},
  {"key":"4,-2,0 @0","familia":null,"shape":[4,-2,0],"arrival":0,"adventus":"in finalem","n":269,"finality":0.446,"modes":{"1":15,"2":43,"6":2,"7":12,"8":100,"12":1,"?":96}},
  {"key":"2,2,0 @2","familia":null,"shape":[2,2,0],"arrival":2,"adventus":"in secundam","n":267,"finality":0.007,"modes":{"1":60,"2":47,"3":8,"4":2,"7":19,"8":123,"12":1,"32":2,"33":3,"82":1,"?":1}},
  {"key":"-2,-2,2 @-5","familia":"descensus simplex","shape":[-2,-2,2],"arrival":-5,"adventus":"in subquartam","n":265,"finality":0.03,"modes":{"1":154,"5":3,"7":98,"8":3,"?":7}},
  {"key":"2,2,-2 @5","familia":null,"shape":[2,2,-2],"arrival":5,"adventus":"in quartam","n":258,"finality":0.035,"modes":{"1":104,"2":5,"3":27,"4":75,"5":2,"6":3,"7":29,"8":4,"?":9}},
  {"key":"-2,-1,-2 @-2","familia":"descensus per semitonium","shape":[-2,-1,-2],"arrival":-2,"adventus":"in subfinalem","n":251,"finality":0.052,"modes":{"3":142,"4":94,"7":6,"?":9}},
  {"key":"0,0,-1 @0","familia":"descensus per semitonium","shape":[0,0,-1],"arrival":0,"adventus":"in finalem","n":249,"finality":0.598,"modes":{"1":1,"2":6,"3":78,"4":147,"5":4,"6":1,"7":3,"8":5,"62":2,"?":2}},
  {"key":"-3,0,-2 @-2","familia":null,"shape":[-3,0,-2],"arrival":-2,"adventus":"in subfinalem","n":248,"finality":0,"modes":{"1":115,"2":79,"3":19,"4":2,"5":3,"7":4,"8":26}},
  {"key":"-1,-2,-2 @-2","familia":null,"shape":[-1,-2,-2],"arrival":-2,"adventus":"in subfinalem","n":248,"finality":0.016,"modes":{"1":142,"2":77,"3":8,"5":1,"6":2,"7":5,"8":10,"82":1,"?":2}},
  {"key":"-2,2,-2 @-5","familia":"flexus","shape":[-2,2,-2],"arrival":-5,"adventus":"in subquartam","n":243,"finality":0.21,"modes":{"1":31,"2":8,"3":6,"4":17,"5":24,"6":9,"7":87,"8":61}},
  {"key":"-2,0,-1 @0","familia":"descensus per semitonium","shape":[-2,0,-1],"arrival":0,"adventus":"in finalem","n":242,"finality":0.686,"modes":{"2":2,"3":61,"4":151,"6":6,"7":18,"8":2,"?":2}},
  {"key":"-1,-4,0 @0","familia":null,"shape":[-1,-4,0],"arrival":0,"adventus":"in finalem","n":242,"finality":0.583,"modes":{"4":1,"7":99,"8":141,"?":1}},
  {"key":"-1,-2,0 @-5","familia":"descensus per semitonium","shape":[-1,-2,0],"arrival":-5,"adventus":"in subquartam","n":239,"finality":0.297,"modes":{"1":158,"2":4,"4":2,"7":44,"8":22,"?":9}},
  {"key":"-2,-3,0 @0","familia":null,"shape":[-2,-3,0],"arrival":0,"adventus":"in finalem","n":235,"finality":0.26,"modes":{"1":71,"2":88,"3":22,"4":45,"5":7,"8":2}},
  {"key":"2,2,-2 @2","familia":null,"shape":[2,2,-2],"arrival":2,"adventus":"in secundam","n":227,"finality":0.026,"modes":{"1":20,"2":6,"3":5,"4":2,"5":16,"6":20,"7":23,"8":131,"72":4}},
  {"key":"-2,2,0 @2","familia":"circuitus infra","shape":[-2,2,0],"arrival":2,"adventus":"in secundam","n":227,"finality":0.004,"modes":{"1":18,"2":146,"4":2,"5":7,"6":4,"7":35,"8":13,"?":2}},
  {"key":"2,-2,0 @3","familia":"tactus supra","shape":[2,-2,0],"arrival":3,"adventus":"in tertiam","n":226,"finality":0.009,"modes":{"1":76,"2":80,"3":9,"4":28,"5":15,"6":2,"7":8,"8":7,"?":1}},
  {"key":"-2,2,-2 @3","familia":"flexus","shape":[-2,2,-2],"arrival":3,"adventus":"in tertiam","n":226,"finality":0.08,"modes":{"1":54,"2":60,"3":43,"4":23,"5":8,"6":3,"7":12,"8":22,"12":1}},
  {"key":"-3,-2,2 @0","familia":null,"shape":[-3,-2,2],"arrival":0,"adventus":"in finalem","n":225,"finality":0.418,"modes":{"1":60,"2":107,"3":2,"4":29,"5":1,"7":2,"8":21,"?":3}},
  {"key":"-2,2,-2 @2","familia":"flexus","shape":[-2,2,-2],"arrival":2,"adventus":"in secundam","n":222,"finality":0.131,"modes":{"1":47,"2":5,"3":9,"4":2,"5":12,"6":81,"7":23,"8":37,"?":6}},
  {"key":"1,-1,-2 @-5","familia":"semitonium circumactum","shape":[1,-1,-2],"arrival":-5,"adventus":"in subquartam","n":219,"finality":0.11,"modes":{"1":72,"2":6,"3":4,"4":4,"7":59,"8":64,"72":9,"?":1}},
  {"key":"0,2,0 @2","familia":null,"shape":[0,2,0],"arrival":2,"adventus":"in secundam","n":219,"finality":0.082,"modes":{"1":80,"2":17,"3":1,"4":4,"5":6,"6":23,"7":4,"8":68,"?":16}},
  {"key":"-2,2,0 @5","familia":"circuitus infra","shape":[-2,2,0],"arrival":5,"adventus":"in quartam","n":218,"finality":0.06,"modes":{"1":21,"2":4,"3":11,"4":150,"7":13,"12":3,"13":1,"?":15}},
  {"key":"0,2,0 @0","familia":null,"shape":[0,2,0],"arrival":0,"adventus":"in finalem","n":217,"finality":0.203,"modes":{"1":39,"2":15,"3":5,"4":51,"6":6,"7":1,"8":89,"32":1,"82":1,"?":9}},
  {"key":"1,-1,-2 @5","familia":"semitonium circumactum","shape":[1,-1,-2],"arrival":5,"adventus":"in quartam","n":212,"finality":0.217,"modes":{"1":75,"2":2,"3":105,"4":9,"5":1,"6":1,"7":4,"8":13,"32":2}},
  {"key":"0,0,0 @3","familia":"repercussio","shape":[0,0,0],"arrival":3,"adventus":"in tertiam","n":208,"finality":0.409,"modes":{"1":16,"2":50,"3":136,"5":5,"6":1}},
  {"key":"-2,-2,-1 @0","familia":null,"shape":[-2,-2,-1],"arrival":0,"adventus":"in finalem","n":208,"finality":0.519,"modes":{"2":1,"3":16,"4":187,"7":4}},
  {"key":"0,2,-2 @3","familia":null,"shape":[0,2,-2],"arrival":3,"adventus":"in tertiam","n":205,"finality":0,"modes":{"1":77,"2":24,"3":2,"4":49,"5":27,"7":12,"8":8,"42":1,"?":5}},
  {"key":"2,1,-1 @-5","familia":null,"shape":[2,1,-1],"arrival":-5,"adventus":"in subquartam","n":203,"finality":0.005,"modes":{"1":116,"2":24,"3":41,"4":13,"7":5,"8":4}},
  {"key":"3,0,-1 @4","familia":null,"shape":[3,0,-1],"arrival":4,"adventus":"in tertiam","n":201,"finality":0,"modes":{"1":1,"4":1,"6":17,"7":50,"8":126,"63":6}},
  {"key":"2,0,2 @0","familia":null,"shape":[2,0,2],"arrival":0,"adventus":"in finalem","n":195,"finality":0.503,"modes":{"1":11,"2":6,"3":6,"4":93,"5":3,"6":28,"7":1,"8":7,"12":8,"62":7,"?":25}},
  {"key":"1,0,-1 @4","familia":null,"shape":[1,0,-1],"arrival":4,"adventus":"in tertiam","n":194,"finality":0.077,"modes":{"1":20,"3":18,"5":37,"6":9,"7":23,"8":70,"62":9,"?":8}},
  {"key":"-2,0,-3 @0","familia":null,"shape":[-2,0,-3],"arrival":0,"adventus":"in finalem","n":192,"finality":0.698,"modes":{"1":29,"2":28,"3":85,"4":34,"5":4,"8":12}},
  {"key":"-1,1,-1 @0","familia":null,"shape":[-1,1,-1],"arrival":0,"adventus":"in finalem","n":192,"finality":0.708,"modes":{"1":19,"2":11,"3":7,"4":13,"5":6,"6":3,"7":50,"8":16,"62":6,"?":61}},
  {"key":"1,-1,-2 @-2","familia":"semitonium circumactum","shape":[1,-1,-2],"arrival":-2,"adventus":"in subfinalem","n":192,"finality":0.172,"modes":{"1":9,"2":20,"3":39,"4":116,"5":1,"7":1,"8":6}},
  {"key":"-3,1,-3 @0","familia":null,"shape":[-3,1,-3],"arrival":0,"adventus":"in finalem","n":188,"finality":0.473,"modes":{"1":93,"2":18,"5":75,"8":1,"?":1}},
  {"key":"1,-3,-2 @-2","familia":null,"shape":[1,-3,-2],"arrival":-2,"adventus":"in subfinalem","n":186,"finality":0,"modes":{"1":26,"2":55,"8":105}},
  {"key":"-2,0,0 @0","familia":null,"shape":[-2,0,0],"arrival":0,"adventus":"in finalem","n":185,"finality":0.822,"modes":{"1":70,"2":23,"3":1,"4":5,"5":1,"6":10,"7":28,"8":47}},
  {"key":"-2,0,-2 @-5","familia":"descensus repercussus","shape":[-2,0,-2],"arrival":-5,"adventus":"in subquartam","n":181,"finality":0.21,"modes":{"1":10,"2":56,"3":1,"4":1,"5":47,"6":7,"8":59}},
  {"key":"2,-4,0 @-2","familia":null,"shape":[2,-4,0],"arrival":-2,"adventus":"in subfinalem","n":177,"finality":0.073,"modes":{"1":5,"2":43,"3":3,"4":2,"5":7,"7":25,"8":90,"?":2}},
  {"key":"1,2,-2 @5","familia":null,"shape":[1,2,-2],"arrival":5,"adventus":"in quartam","n":174,"finality":0,"modes":{"7":29,"8":144,"?":1}},
  {"key":"4,0,-2 @0","familia":null,"shape":[4,0,-2],"arrival":0,"adventus":"in finalem","n":174,"finality":0.626,"modes":{"1":56,"2":52,"7":33,"8":33}},
  {"key":"0,2,-2 @5","familia":null,"shape":[0,2,-2],"arrival":5,"adventus":"in quartam","n":174,"finality":0,"modes":{"1":16,"2":8,"3":28,"4":8,"5":14,"6":1,"7":45,"8":47,"?":7}},
  {"key":"-2,0,-2 @-4","familia":"descensus repercussus","shape":[-2,0,-2],"arrival":-4,"adventus":"in subtertiam","n":172,"finality":0.174,"modes":{"1":3,"2":46,"3":22,"4":25,"5":13,"6":14,"7":7,"8":37,"62":1,"?":4}},
  {"key":"2,-2,-2 @-4","familia":null,"shape":[2,-2,-2],"arrival":-4,"adventus":"in subtertiam","n":172,"finality":0.436,"modes":{"1":46,"2":17,"3":5,"4":54,"5":10,"6":9,"7":14,"8":3,"?":14}},
  {"key":"3,2,-2 @0","familia":null,"shape":[3,2,-2],"arrival":0,"adventus":"in finalem","n":165,"finality":0.673,"modes":{"1":4,"4":6,"5":20,"6":66,"7":4,"8":65}},
  {"key":"-1,3,2 @4","familia":null,"shape":[-1,3,2],"arrival":4,"adventus":"in tertiam","n":165,"finality":0.279,"modes":{"1":7,"3":3,"4":2,"6":81,"7":11,"8":7,"?":54}},
  {"key":"1,0,-1 @2","familia":null,"shape":[1,0,-1],"arrival":2,"adventus":"in secundam","n":164,"finality":0.055,"modes":{"1":15,"2":98,"3":15,"4":17,"5":12,"7":3,"8":4}},
  {"key":"2,-2,0 @2","familia":"tactus supra","shape":[2,-2,0],"arrival":2,"adventus":"in secundam","n":164,"finality":0.037,"modes":{"1":8,"2":10,"3":5,"4":5,"5":10,"6":49,"7":38,"8":22,"72":1,"?":16}},
  {"key":"2,-2,0 @-2","familia":"tactus supra","shape":[2,-2,0],"arrival":-2,"adventus":"in subfinalem","n":160,"finality":0.056,"modes":{"1":15,"2":21,"3":9,"4":8,"5":9,"6":14,"7":12,"8":35,"32":2,"?":35}},
  {"key":"-2,-1,-2 @-5","familia":"descensus per semitonium","shape":[-2,-1,-2],"arrival":-5,"adventus":"in subquartam","n":159,"finality":0.013,"modes":{"1":37,"2":5,"3":1,"7":23,"8":90,"?":3}},
  {"key":"0,0,-3 @0","familia":null,"shape":[0,0,-3],"arrival":0,"adventus":"in finalem","n":157,"finality":0.541,"modes":{"1":76,"2":62,"3":7,"4":4,"5":2,"?":6}},
  {"key":"2,0,0 @-5","familia":null,"shape":[2,0,0],"arrival":-5,"adventus":"in subquartam","n":157,"finality":0.038,"modes":{"1":13,"3":114,"4":6,"5":3,"7":18,"8":3}},
  {"key":"0,0,0 @-5","familia":"repercussio","shape":[0,0,0],"arrival":-5,"adventus":"in subquartam","n":156,"finality":0.526,"modes":{"1":44,"3":3,"4":2,"5":21,"7":81,"8":1,"72":4}},
  {"key":"-1,-2,-2 @5","familia":null,"shape":[-1,-2,-2],"arrival":5,"adventus":"in quartam","n":155,"finality":0.032,"modes":{"1":37,"2":1,"6":2,"7":10,"8":92,"?":13}},
  {"key":"-2,-2,-1 @2","familia":null,"shape":[-2,-2,-1],"arrival":2,"adventus":"in secundam","n":155,"finality":0.013,"modes":{"1":144,"2":10,"4":1}},
  {"key":"-1,-2,-2 @3","familia":null,"shape":[-1,-2,-2],"arrival":3,"adventus":"in tertiam","n":155,"finality":0.058,"modes":{"1":3,"3":128,"4":6,"8":5,"?":13}},
  {"key":"-2,0,2 @0","familia":null,"shape":[-2,0,2],"arrival":0,"adventus":"in finalem","n":154,"finality":0.344,"modes":{"1":110,"2":7,"4":23,"5":1,"6":2,"7":1,"8":5,"12":1,"?":4}},
  {"key":"-2,0,-2 @5","familia":"descensus repercussus","shape":[-2,0,-2],"arrival":5,"adventus":"in quartam","n":153,"finality":0.078,"modes":{"1":27,"2":16,"3":1,"4":1,"5":9,"6":11,"7":21,"8":67}},
  {"key":"2,0,2 @-5","familia":null,"shape":[2,0,2],"arrival":-5,"adventus":"in subquartam","n":153,"finality":0.026,"modes":{"1":105,"2":33,"3":9,"6":5,"7":1}},
  {"key":"0,-2,2 @0","familia":null,"shape":[0,-2,2],"arrival":0,"adventus":"in finalem","n":152,"finality":0.112,"modes":{"1":6,"2":10,"3":6,"4":7,"5":2,"7":1,"8":117,"12":1,"32":1,"?":1}},
  {"key":"-3,0,-2 @3","familia":null,"shape":[-3,0,-2],"arrival":3,"adventus":"in tertiam","n":150,"finality":0.007,"modes":{"1":27,"2":73,"3":38,"4":8,"7":1,"8":3}},
  {"key":"-2,-1,0 @-5","familia":"descensus per semitonium","shape":[-2,-1,0],"arrival":-5,"adventus":"in subquartam","n":150,"finality":0.833,"modes":{"1":5,"3":130,"4":7,"32":3,"33":2,"42":1,"?":2}},
  {"key":"-2,-2,0 @-5","familia":"descensus simplex","shape":[-2,-2,0],"arrival":-5,"adventus":"in subquartam","n":150,"finality":0.24,"modes":{"1":4,"2":2,"5":71,"6":38,"7":26,"8":8,"72":1}},
];
