// AUTO-GENERATED by scripts/bake-cadentiae.mjs — do not edit manually
// (No timestamp by design: identical input must bake to an identical file,
// or every regeneration churns the diff. Git carries the dates.)
// ---------------------------------------------------------------------------
// data/cadentiae — the corpus-grounded cadence catalogue (CADENTIAE)
// ---------------------------------------------------------------------------
// Every phrase-end in the corpus tonus SHIPS (am, ams, cot, cse, gr, la, lh, lu, nr, psm — 26787
// ends), keyed by the last <=4 notes' interval signature in semitones (the
// shape — the gesture) and the closing note's offset from the CHANT'S OWN
// closing note (its sounded final — not the labeled mode's final), as a SIGNED
// semitone count (the arrival — the function).
//
// The arrival is deliberately not octave-reduced: the mod-12 fold pooled a
// fifth ABOVE the final with a fourth BELOW — measured, 3,499 of
// 27,985 phrase ends landed on @-5, of which 2,427 were really +7. Two
// opposite gestures under one key. Folding survives as a degree field on a live
// cadence event, where it is the scale degree and mode-theoretically real.
//
// The population is the SUNG corpus, not the printed books: this table and the
// census now count the same chants, which they never did before. No Latin
// arrival names ride the table, for the same reason no family names do:
// the key carries the arrival; the reader can count. Families with n >= 50 are tabled here (110 families,
// 56.8% of all phrase-ends); the full tally lives in the mining
// artifact. finality = share of a family's occurrences at a final close
// ("::" or chant end) — measured function, continuous, corpus-derived.
//
// This is inventa, not tradita: a computed catalogue with stated method and
// open code ("tonus catalogue, method §cadentiae"). Families are identified by
// their key alone — the shape and its arrival; no editorial names ride the
// table. Method + display doctrine: working/design-analysis-track.md §CADENTIAE.

/** One corpus cadence family: a (shape, arrival) pair with its statistics. */
export interface CadentiaFamilia {
  /** "shape @arrival", e.g. "2,0,-2 @0" — joins mining/census artifacts. */
  key: string;
  /** Interval signature in semitones between the tail's consecutive notes. */
  shape: number[];
  /** Closing note minus the chant's own closing note (sounded final),
   *  in SIGNED semitones — not octave-reduced; see the arrival note above. */
  arrival: number;
  /** Corpus occurrences. */
  n: number;
  /** `n` over ALL phrase-ends (CADENTIAE_POPULATION.ends) — not over the
   *  tabled subset, which would flatter every family that cleared the floor. */
  share: number;
  /** Share of occurrences at a final close — the measured finality index. */
  finality: number;
  /** Occurrences by mode digit ("1".."8"; "?" = mode-less chants). */
  modes: Record<string, number>;
}

/**
 * The denominator behind every `share`: all phrase-ends in the sung corpus,
 * and the same total per mode digit. Both are the FULL tally, never summed
 * from the tabled families — a family's mode counts divided by the tabled
 * subset would overstate every one of them.
 *
 * With `byMode`, a family's lift in a given mode is one division:
 * `(modes[m] / byMode[m]) / share` — how much more (or less) that mode
 * reaches for this close than the corpus at large. Baked as vocabulary, not
 * as arithmetic: the ratio is the caller's to take.
 */
export const CADENTIAE_POPULATION: {
  readonly ends: number;
  readonly byMode: Readonly<Record<string, number>>;
} = Object.freeze({
  ends: 26787,
  byMode: Object.freeze({"1":5180,"2":3704,"3":2640,"4":2700,"5":2770,"6":1597,"7":3335,"8":4610,"?":251}),
});

/** The cadence catalogue, most frequent family first. */
export const CADENTIAE: CadentiaFamilia[] = [
  {"key":"2,0,-2 @0","shape":[2,0,-2],"arrival":0,"n":1116,"share":0.0417,"finality":0.43,"modes":{"1":153,"2":204,"3":34,"4":8,"5":142,"6":143,"7":109,"8":321,"?":2}},
  {"key":"2,-2,0 @0","shape":[2,-2,0],"arrival":0,"n":785,"share":0.0293,"finality":0.397,"modes":{"1":82,"2":131,"3":7,"4":4,"5":91,"6":148,"7":106,"8":200,"?":16}},
  {"key":"-2,0,-2 @0","shape":[-2,0,-2],"arrival":0,"n":581,"share":0.0217,"finality":0.685,"modes":{"1":6,"2":24,"3":2,"4":2,"5":174,"6":27,"7":118,"8":227,"?":1}},
  {"key":"-2,2,0 @0","shape":[-2,2,0],"arrival":0,"n":537,"share":0.02,"finality":0.436,"modes":{"1":115,"2":124,"3":7,"4":50,"7":60,"8":169,"?":12}},
  {"key":"1,-1,-2 @0","shape":[1,-1,-2],"arrival":0,"n":349,"share":0.013,"finality":0.484,"modes":{"1":238,"2":80,"3":1,"4":8,"5":5,"7":8,"8":9}},
  {"key":"-2,2,-2 @0","shape":[-2,2,-2],"arrival":0,"n":341,"share":0.0127,"finality":0.302,"modes":{"1":33,"2":38,"3":11,"4":3,"5":22,"6":14,"7":48,"8":171,"?":1}},
  {"key":"2,0,-2 @-2","shape":[2,0,-2],"arrival":-2,"n":333,"share":0.0124,"finality":0.228,"modes":{"1":63,"2":51,"3":50,"4":13,"5":36,"6":6,"7":22,"8":74,"?":18}},
  {"key":"2,-2,-2 @0","shape":[2,-2,-2],"arrival":0,"n":277,"share":0.0103,"finality":0.498,"modes":{"1":27,"2":3,"3":7,"5":22,"6":44,"7":52,"8":121,"?":1}},
  {"key":"-2,0,-2 @-2","shape":[-2,0,-2],"arrival":-2,"n":264,"share":0.0099,"finality":0.068,"modes":{"1":78,"2":68,"3":1,"4":2,"5":2,"7":13,"8":100}},
  {"key":"2,2,-2 @0","shape":[2,2,-2],"arrival":0,"n":258,"share":0.0096,"finality":0.438,"modes":{"1":48,"2":121,"3":8,"4":2,"5":1,"6":6,"7":18,"8":54}},
  {"key":"2,0,-2 @3","shape":[2,0,-2],"arrival":3,"n":254,"share":0.0095,"finality":0.035,"modes":{"1":48,"2":53,"3":32,"4":53,"5":39,"6":3,"7":8,"8":12,"?":6}},
  {"key":"-3,2,-2 @0","shape":[-3,2,-2],"arrival":0,"n":240,"share":0.009,"finality":0.292,"modes":{"1":89,"2":113,"3":17,"4":14,"5":6,"7":1}},
  {"key":"-2,-1,0 @0","shape":[-2,-1,0],"arrival":0,"n":229,"share":0.0085,"finality":0.69,"modes":{"3":95,"4":130,"6":1,"?":3}},
  {"key":"-1,-2,0 @0","shape":[-1,-2,0],"arrival":0,"n":227,"share":0.0085,"finality":0.59,"modes":{"1":139,"2":66,"3":15,"7":1,"8":3,"?":3}},
  {"key":"-2,-2,2 @0","shape":[-2,-2,2],"arrival":0,"n":220,"share":0.0082,"finality":0.441,"modes":{"1":73,"2":73,"3":7,"4":4,"5":13,"7":12,"8":37,"?":1}},
  {"key":"-2,-2,0 @0","shape":[-2,-2,0],"arrival":0,"n":220,"share":0.0082,"finality":0.536,"modes":{"1":4,"4":2,"5":22,"6":80,"7":30,"8":81,"?":1}},
  {"key":"2,-4,2 @0","shape":[2,-4,2],"arrival":0,"n":212,"share":0.0079,"finality":0.689,"modes":{"1":18,"2":13,"3":127,"4":3,"7":16,"8":34,"?":1}},
  {"key":"-2,2,-2 @-2","shape":[-2,2,-2],"arrival":-2,"n":210,"share":0.0078,"finality":0.119,"modes":{"1":22,"2":48,"3":11,"4":53,"5":1,"7":24,"8":45,"?":6}},
  {"key":"2,-2,-2 @-2","shape":[2,-2,-2],"arrival":-2,"n":206,"share":0.0077,"finality":0.126,"modes":{"1":57,"2":74,"3":7,"7":11,"8":56,"?":1}},
  {"key":"0,-2,0 @0","shape":[0,-2,0],"arrival":0,"n":204,"share":0.0076,"finality":0.544,"modes":{"1":33,"2":11,"4":1,"6":49,"7":14,"8":93,"?":3}},
  {"key":"2,1,-3 @0","shape":[2,1,-3],"arrival":0,"n":195,"share":0.0073,"finality":0.938,"modes":{"1":67,"2":125,"3":2,"5":1}},
  {"key":"1,-3,0 @0","shape":[1,-3,0],"arrival":0,"n":185,"share":0.0069,"finality":0.27,"modes":{"1":99,"2":62,"3":1,"4":14,"5":8,"7":1}},
  {"key":"0,0,-1 @0","shape":[0,0,-1],"arrival":0,"n":166,"share":0.0062,"finality":0.627,"modes":{"2":2,"3":53,"4":103,"5":3,"6":1,"7":1,"8":3}},
  {"key":"-2,-1,-2 @0","shape":[-2,-1,-2],"arrival":0,"n":163,"share":0.0061,"finality":0.325,"modes":{"1":118,"2":25,"5":1,"7":19}},
  {"key":"2,0,-2 @-4","shape":[2,0,-2],"arrival":-4,"n":159,"share":0.0059,"finality":0.472,"modes":{"1":21,"2":5,"3":17,"4":6,"5":35,"6":14,"7":33,"8":21,"?":7}},
  {"key":"0,0,0 @3","shape":[0,0,0],"arrival":3,"n":153,"share":0.0057,"finality":0.392,"modes":{"1":16,"2":33,"3":101,"5":2,"6":1}},
  {"key":"-1,-2,-2 @0","shape":[-1,-2,-2],"arrival":0,"n":152,"share":0.0057,"finality":0.368,"modes":{"2":2,"3":1,"4":1,"5":19,"6":24,"7":14,"8":90,"?":1}},
  {"key":"2,0,-2 @5","shape":[2,0,-2],"arrival":5,"n":151,"share":0.0056,"finality":0.073,"modes":{"1":39,"2":41,"3":7,"4":12,"5":21,"6":2,"7":5,"8":23,"?":1}},
  {"key":"0,2,-2 @0","shape":[0,2,-2],"arrival":0,"n":147,"share":0.0055,"finality":0.177,"modes":{"1":14,"2":22,"3":3,"4":2,"5":14,"6":32,"7":9,"8":51}},
  {"key":"2,-4,0 @0","shape":[2,-4,0],"arrival":0,"n":146,"share":0.0055,"finality":0.466,"modes":{"5":33,"6":58,"7":15,"8":40}},
  {"key":"-3,0,-2 @0","shape":[-3,0,-2],"arrival":0,"n":139,"share":0.0052,"finality":0.065,"modes":{"1":3,"2":28,"4":2,"5":9,"7":8,"8":89}},
  {"key":"2,0,-2 @2","shape":[2,0,-2],"arrival":2,"n":138,"share":0.0052,"finality":0.297,"modes":{"1":9,"2":16,"3":14,"4":2,"5":14,"6":45,"7":13,"8":21,"?":4}},
  {"key":"-4,2,0 @0","shape":[-4,2,0],"arrival":0,"n":134,"share":0.005,"finality":0.261,"modes":{"1":66,"2":32,"4":1,"7":10,"8":25}},
  {"key":"-1,0,-2 @0","shape":[-1,0,-2],"arrival":0,"n":130,"share":0.0049,"finality":0.346,"modes":{"1":54,"2":40,"3":1,"4":1,"7":27,"8":7}},
  {"key":"2,1,-1 @4","shape":[2,1,-1],"arrival":4,"n":128,"share":0.0048,"finality":0.141,"modes":{"1":14,"2":1,"3":3,"4":4,"5":12,"6":54,"7":15,"8":25}},
  {"key":"-2,0,-1 @0","shape":[-2,0,-1],"arrival":0,"n":127,"share":0.0047,"finality":0.669,"modes":{"2":1,"3":41,"4":73,"6":6,"7":4,"8":2}},
  {"key":"2,0,-2 @7","shape":[2,0,-2],"arrival":7,"n":124,"share":0.0046,"finality":0.008,"modes":{"1":10,"3":1,"5":72,"7":38,"8":3}},
  {"key":"2,0,-2 @-7","shape":[2,0,-2],"arrival":-7,"n":124,"share":0.0046,"finality":0.306,"modes":{"1":21,"2":14,"3":9,"4":4,"5":12,"6":3,"7":35,"8":26}},
  {"key":"2,1,-1 @0","shape":[2,1,-1],"arrival":0,"n":123,"share":0.0046,"finality":0.293,"modes":{"1":11,"2":7,"3":27,"4":60,"5":6,"6":2,"7":7,"8":3}},
  {"key":"0,0,0 @7","shape":[0,0,0],"arrival":7,"n":115,"share":0.0043,"finality":0.539,"modes":{"1":29,"3":2,"5":18,"7":66}},
  {"key":"-5,0,-2 @-2","shape":[-5,0,-2],"arrival":-2,"n":114,"share":0.0043,"finality":0.035,"modes":{"1":28,"2":31,"3":7,"7":6,"8":42}},
  {"key":"2,-2,0 @7","shape":[2,-2,0],"arrival":7,"n":113,"share":0.0042,"finality":0,"modes":{"1":29,"5":42,"6":5,"7":35,"8":2}},
  {"key":"1,-3,-2 @0","shape":[1,-3,-2],"arrival":0,"n":113,"share":0.0042,"finality":0.558,"modes":{"5":11,"7":21,"8":80,"?":1}},
  {"key":"2,-2,0 @3","shape":[2,-2,0],"arrival":3,"n":112,"share":0.0042,"finality":0,"modes":{"1":37,"2":46,"3":6,"4":15,"5":3,"6":2,"7":1,"8":1,"?":1}},
  {"key":"-2,2,-2 @5","shape":[-2,2,-2],"arrival":5,"n":111,"share":0.0041,"finality":0.081,"modes":{"1":35,"2":2,"3":3,"4":17,"7":7,"8":47}},
  {"key":"-2,0,-3 @0","shape":[-2,0,-3],"arrival":0,"n":109,"share":0.0041,"finality":0.743,"modes":{"1":21,"2":10,"3":50,"4":18,"5":3,"8":7}},
  {"key":"-3,0,-2 @-2","shape":[-3,0,-2],"arrival":-2,"n":106,"share":0.004,"finality":0,"modes":{"1":40,"2":35,"3":8,"4":2,"5":3,"7":3,"8":15}},
  {"key":"2,0,0 @0","shape":[2,0,0],"arrival":0,"n":102,"share":0.0038,"finality":0.451,"modes":{"1":18,"2":13,"3":2,"4":37,"8":32}},
  {"key":"2,-2,-3 @0","shape":[2,-2,-3],"arrival":0,"n":99,"share":0.0037,"finality":0.626,"modes":{"1":25,"2":8,"3":15,"4":44,"5":3,"8":4}},
  {"key":"2,-2,0 @5","shape":[2,-2,0],"arrival":5,"n":99,"share":0.0037,"finality":0.03,"modes":{"1":13,"2":20,"3":2,"4":9,"5":2,"6":3,"7":20,"8":27,"?":3}},
  {"key":"-2,0,-2 @3","shape":[-2,0,-2],"arrival":3,"n":99,"share":0.0037,"finality":0.02,"modes":{"1":32,"2":7,"3":48,"5":2,"6":1,"7":2,"8":7}},
  {"key":"2,0,-2 @-5","shape":[2,0,-2],"arrival":-5,"n":97,"share":0.0036,"finality":0.258,"modes":{"1":11,"2":8,"3":3,"4":4,"5":6,"6":14,"7":20,"8":31}},
  {"key":"2,-2,-2 @3","shape":[2,-2,-2],"arrival":3,"n":96,"share":0.0036,"finality":0.146,"modes":{"1":39,"2":36,"3":17,"4":2,"5":1,"8":1}},
  {"key":"0,-3,-2 @0","shape":[0,-3,-2],"arrival":0,"n":96,"share":0.0036,"finality":0.854,"modes":{"6":2,"7":92,"8":2}},
  {"key":"2,1,-1 @7","shape":[2,1,-1],"arrival":7,"n":96,"share":0.0036,"finality":0,"modes":{"1":64,"2":7,"3":21,"4":3,"8":1}},
  {"key":"-2,2,-2 @3","shape":[-2,2,-2],"arrival":3,"n":93,"share":0.0035,"finality":0.065,"modes":{"1":21,"2":30,"3":15,"4":10,"5":2,"7":8,"8":7}},
  {"key":"-2,-2,0 @-2","shape":[-2,-2,0],"arrival":-2,"n":90,"share":0.0034,"finality":0.089,"modes":{"1":16,"2":24,"3":4,"4":1,"5":1,"6":8,"7":4,"8":31,"?":1}},
  {"key":"-2,2,0 @7","shape":[-2,2,0],"arrival":7,"n":89,"share":0.0033,"finality":0,"modes":{"1":22,"2":3,"3":2,"7":58,"8":3,"?":1}},
  {"key":"0,0,-3 @0","shape":[0,0,-3],"arrival":0,"n":88,"share":0.0033,"finality":0.568,"modes":{"1":50,"2":34,"3":2,"4":1,"5":1}},
  {"key":"-2,0,-2 @-5","shape":[-2,0,-2],"arrival":-5,"n":86,"share":0.0032,"finality":0.198,"modes":{"1":6,"2":23,"3":1,"5":25,"6":4,"8":27}},
  {"key":"2,-2,-2 @-4","shape":[2,-2,-2],"arrival":-4,"n":85,"share":0.0032,"finality":0.412,"modes":{"1":21,"2":2,"3":1,"4":26,"5":3,"6":14,"7":2,"8":2,"?":14}},
  {"key":"1,0,-1 @0","shape":[1,0,-1],"arrival":0,"n":84,"share":0.0031,"finality":0.274,"modes":{"1":6,"3":5,"4":42,"5":21,"6":1,"7":9}},
  {"key":"2,2,-2 @2","shape":[2,2,-2],"arrival":2,"n":83,"share":0.0031,"finality":0,"modes":{"1":10,"4":2,"5":14,"6":8,"7":12,"8":37}},
  {"key":"0,0,0 @5","shape":[0,0,0],"arrival":5,"n":82,"share":0.0031,"finality":0.22,"modes":{"2":8,"4":34,"5":5,"7":2,"8":33}},
  {"key":"3,0,0 @3","shape":[3,0,0],"arrival":3,"n":79,"share":0.0029,"finality":0.165,"modes":{"1":2,"3":63,"5":13,"7":1}},
  {"key":"3,2,-2 @0","shape":[3,2,-2],"arrival":0,"n":79,"share":0.0029,"finality":0.646,"modes":{"1":3,"4":6,"5":10,"6":48,"7":2,"8":10}},
  {"key":"2,2,0 @7","shape":[2,2,0],"arrival":7,"n":76,"share":0.0028,"finality":0,"modes":{"1":44,"2":17,"3":7,"8":1,"?":7}},
  {"key":"-2,2,-2 @2","shape":[-2,2,-2],"arrival":2,"n":75,"share":0.0028,"finality":0.16,"modes":{"1":8,"2":3,"3":4,"4":2,"5":10,"6":21,"7":13,"8":14}},
  {"key":"2,-4,0 @-2","shape":[2,-4,0],"arrival":-2,"n":73,"share":0.0027,"finality":0.082,"modes":{"1":2,"2":29,"3":1,"4":2,"5":2,"7":15,"8":22}},
  {"key":"-2,0,-2 @-4","shape":[-2,0,-2],"arrival":-4,"n":73,"share":0.0027,"finality":0.151,"modes":{"2":23,"3":7,"4":10,"5":7,"6":9,"7":3,"8":14}},
  {"key":"-2,2,-2 @-5","shape":[-2,2,-2],"arrival":-5,"n":73,"share":0.0027,"finality":0.329,"modes":{"1":1,"2":5,"3":2,"4":10,"5":2,"6":7,"7":11,"8":35}},
  {"key":"4,-2,0 @0","shape":[4,-2,0],"arrival":0,"n":72,"share":0.0027,"finality":0.208,"modes":{"1":12,"2":30,"6":2,"7":9,"8":19}},
  {"key":"3,-1,-2 @0","shape":[3,-1,-2],"arrival":0,"n":71,"share":0.0027,"finality":0.296,"modes":{"1":32,"2":25,"3":8,"7":1,"8":2,"?":3}},
  {"key":"3,-1,-4 @0","shape":[3,-1,-4],"arrival":0,"n":70,"share":0.0026,"finality":0.786,"modes":{"5":59,"8":11}},
  {"key":"0,2,-2 @7","shape":[0,2,-2],"arrival":7,"n":70,"share":0.0026,"finality":0,"modes":{"1":11,"3":1,"5":46,"7":10,"8":2}},
  {"key":"-2,2,0 @2","shape":[-2,2,0],"arrival":2,"n":70,"share":0.0026,"finality":0,"modes":{"1":5,"2":34,"5":4,"6":4,"7":19,"8":4}},
  {"key":"2,2,-2 @7","shape":[2,2,-2],"arrival":7,"n":70,"share":0.0026,"finality":0,"modes":{"1":1,"2":2,"6":1,"7":60,"8":5,"?":1}},
  {"key":"-4,2,-2 @0","shape":[-4,2,-2],"arrival":0,"n":69,"share":0.0026,"finality":0.551,"modes":{"3":1,"5":49,"6":6,"7":9,"8":4}},
  {"key":"-1,-4,2 @0","shape":[-1,-4,2],"arrival":0,"n":69,"share":0.0026,"finality":0.362,"modes":{"1":52,"2":15,"4":1,"7":1}},
  {"key":"1,-3,-2 @-2","shape":[1,-3,-2],"arrival":-2,"n":68,"share":0.0025,"finality":0,"modes":{"1":9,"2":29,"8":30}},
  {"key":"-3,1,-3 @0","shape":[-3,1,-3],"arrival":0,"n":68,"share":0.0025,"finality":0.456,"modes":{"1":32,"2":7,"5":29}},
  {"key":"2,2,0 @2","shape":[2,2,0],"arrival":2,"n":67,"share":0.0025,"finality":0.015,"modes":{"1":22,"2":12,"3":7,"7":5,"8":21}},
  {"key":"1,0,-1 @2","shape":[1,0,-1],"arrival":2,"n":66,"share":0.0025,"finality":0.045,"modes":{"1":7,"2":37,"3":8,"4":3,"5":7,"7":3,"8":1}},
  {"key":"4,0,-2 @0","shape":[4,0,-2],"arrival":0,"n":66,"share":0.0025,"finality":0.561,"modes":{"1":29,"2":20,"7":16,"8":1}},
  {"key":"-3,0,-2 @3","shape":[-3,0,-2],"arrival":3,"n":65,"share":0.0024,"finality":0,"modes":{"1":14,"2":17,"3":26,"4":5,"7":1,"8":2}},
  {"key":"-3,2,-2 @-2","shape":[-3,2,-2],"arrival":-2,"n":64,"share":0.0024,"finality":0,"modes":{"3":40,"4":24}},
  {"key":"-1,-2,-2 @-2","shape":[-1,-2,-2],"arrival":-2,"n":64,"share":0.0024,"finality":0,"modes":{"1":26,"2":33,"3":2,"6":2,"7":1}},
  {"key":"2,-2,0 @2","shape":[2,-2,0],"arrival":2,"n":64,"share":0.0024,"finality":0.062,"modes":{"1":4,"2":3,"5":10,"6":21,"7":11,"8":14,"?":1}},
  {"key":"-2,-3,0 @0","shape":[-2,-3,0],"arrival":0,"n":63,"share":0.0024,"finality":0.175,"modes":{"1":12,"2":35,"3":3,"4":7,"5":6}},
  {"key":"-1,1,-3 @0","shape":[-1,1,-3],"arrival":0,"n":61,"share":0.0023,"finality":0.279,"modes":{"1":33,"2":21,"3":6,"5":1}},
  {"key":"-2,-2,0 @3","shape":[-2,-2,0],"arrival":3,"n":60,"share":0.0022,"finality":0,"modes":{"1":18,"2":15,"3":15,"4":9,"5":1,"7":1,"8":1}},
  {"key":" @0","shape":[],"arrival":0,"n":60,"share":0.0022,"finality":1,"modes":{"1":12,"2":4,"3":6,"4":4,"5":5,"6":4,"7":15,"8":10}},
  {"key":"2,2,-2 @5","shape":[2,2,-2],"arrival":5,"n":59,"share":0.0022,"finality":0.017,"modes":{"1":29,"2":4,"3":4,"4":16,"5":1,"7":5}},
  {"key":"0,0,-1 @-5","shape":[0,0,-1],"arrival":-5,"n":59,"share":0.0022,"finality":0.712,"modes":{"3":45,"4":14}},
  {"key":"1,-1,-2 @-5","shape":[1,-1,-2],"arrival":-5,"n":59,"share":0.0022,"finality":0.22,"modes":{"1":15,"2":2,"3":1,"4":6,"7":5,"8":30}},
  {"key":"-1,1,-1 @4","shape":[-1,1,-1],"arrival":4,"n":58,"share":0.0022,"finality":0.224,"modes":{"1":2,"5":2,"7":52,"8":2}},
  {"key":"-2,-1,0 @-5","shape":[-2,-1,0],"arrival":-5,"n":58,"share":0.0022,"finality":1,"modes":{"3":57,"4":1}},
  {"key":"-2,2,-5 @-5","shape":[-2,2,-5],"arrival":-5,"n":57,"share":0.0021,"finality":0,"modes":{"1":11,"2":22,"3":6,"4":9,"8":9}},
  {"key":"2,-2,0 @-2","shape":[2,-2,0],"arrival":-2,"n":57,"share":0.0021,"finality":0.105,"modes":{"1":5,"2":7,"3":3,"4":3,"5":7,"6":2,"7":5,"8":21,"?":4}},
  {"key":"-1,1,2 @5","shape":[-1,1,2],"arrival":5,"n":56,"share":0.0021,"finality":0.018,"modes":{"1":25,"2":30,"5":1}},
  {"key":"2,-2,-1 @0","shape":[2,-2,-1],"arrival":0,"n":56,"share":0.0021,"finality":0.411,"modes":{"1":1,"3":7,"4":42,"5":3,"7":3}},
  {"key":"-5,0,-2 @0","shape":[-5,0,-2],"arrival":0,"n":56,"share":0.0021,"finality":0.054,"modes":{"4":1,"5":15,"6":2,"7":32,"8":6}},
  {"key":"0,-1,-2 @0","shape":[0,-1,-2],"arrival":0,"n":55,"share":0.0021,"finality":0.382,"modes":{"1":12,"2":21,"3":4,"4":13,"5":4,"8":1}},
  {"key":"0,0,-3 @4","shape":[0,0,-3],"arrival":4,"n":55,"share":0.0021,"finality":0,"modes":{"5":55}},
  {"key":"-3,2,-2 @4","shape":[-3,2,-2],"arrival":4,"n":54,"share":0.002,"finality":0,"modes":{"1":1,"5":53}},
  {"key":"-3,-2,2 @0","shape":[-3,-2,2],"arrival":0,"n":53,"share":0.002,"finality":0.245,"modes":{"1":2,"2":32,"3":2,"4":2,"5":1,"7":1,"8":12,"?":1}},
  {"key":"0,2,-2 @3","shape":[0,2,-2],"arrival":3,"n":53,"share":0.002,"finality":0,"modes":{"1":10,"2":10,"3":1,"4":14,"5":7,"7":7,"8":4}},
  {"key":"-2,0,-3 @4","shape":[-2,0,-3],"arrival":4,"n":52,"share":0.0019,"finality":0,"modes":{"5":42,"7":10}},
  {"key":"-2,2,0 @5","shape":[-2,2,0],"arrival":5,"n":51,"share":0.0019,"finality":0,"modes":{"1":7,"2":6,"3":4,"4":26,"?":8}},
  {"key":"0,-2,2 @0","shape":[0,-2,2],"arrival":0,"n":51,"share":0.0019,"finality":0.078,"modes":{"1":5,"2":6,"3":6,"8":34}},
];

// THE index, built once and shared. Every consumer joins on the family key, so
// each one that builds its own Map is a third copy of the same lookup — the
// renderer had one, the score builder needed one, and any caller wanting a
// family's statistics had to write a fourth.
let _index: Map<string, CadentiaFamilia> | null = null;

/**
 * The catalogued family for a cadence signature, or undefined when the
 * signature falls below the table's floor. Deferred: a caller who never asks
 * does not pay for the Map.
 */
export function cadentiaFamilia(key: string): CadentiaFamilia | undefined {
  if (!_index) _index = new Map(CADENTIAE.map((f) => [f.key, f]));
  return _index.get(key);
}
