// AUTO-GENERATED by scripts/extract-commune-office.mjs — do not edit manually
// The OFFICE half of the Commune of Saints: the antiphons, invitatory, hymn
// and responsories a category of saint sings when the day has no proper ones.
// 1239 texts bound across 53 communes.

import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

/** commune → hour → slot → chant ids, in liturgical order. */
export type CommuneOfficeTable = Record<string, Record<string, Record<string, string[]>>>;

const __dir = dirname(fileURLToPath(import.meta.url));
export const COMMUNE_OFFICE: CommuneOfficeTable = (
  JSON.parse(readFileSync(resolve(__dir, "commune-office.json"), "utf8")) as {
    map: CommuneOfficeTable;
  }
).map;
