// AUTO-GENERATED by scripts/extract-commune.mjs — do not edit manually
// Generated: 2026-03-28T23:14:43.930Z

export interface CommuneProperSet {
  commune: string;
  name: string;
  in: string | null;
  gr: string | null;
  al: string | null;
  tr: string | null;
  of: string | null;
  co: string | null;
}

export interface FeastCommune {
  feastId: string;
  commune: string;
}

export const COMMUNE_PROPERS: CommuneProperSet[] = [
  {
    commune: "C10",
    name: "BMV Sabbato",
    in: "gregobase:1140",
    gr: "gregobase:392",
    al: null,
    tr: null,
    of: "gregobase:210",
    co: "gregobase:160",
  },
  {
    commune: "C10Pasc",
    name: "C10Pasc",
    in: null,
    gr: null,
    al: null,
    tr: null,
    of: "gregobase:567",
    co: null,
  },
  {
    commune: "C10a",
    name: "BMV Sabbato Adv.",
    in: "gregobase:79",
    gr: "gregobase:756",
    al: "gregobase:1209",
    tr: null,
    of: null,
    co: "gregobase:1144",
  },
  {
    commune: "C10b",
    name: "BMV Sabbato Nat.",
    in: "gregobase:124",
    gr: "gregobase:1354",
    al: "gregobase:127",
    tr: "gregobase:1354",
    of: "gregobase:280",
    co: null,
  },
  {
    commune: "C10c",
    name: "BMV Sabbato Pasc.",
    in: null,
    gr: "gregobase:392",
    al: "gregobase:281",
    tr: "gregobase:392",
    of: "gregobase:280",
    co: null,
  },
  {
    commune: "C11",
    name: "Assumptione",
    in: "gregobase:1140",
    gr: "gregobase:392",
    al: "gregobase:127",
    tr: "gregobase:392",
    of: "gregobase:210",
    co: "gregobase:160",
  },
  {
    commune: "C1v",
    name: "Evangelistarum",
    in: "gregobase:163",
    gr: "gregobase:34",
    al: null,
    tr: null,
    of: "gregobase:407",
    co: "gregobase:365",
  },
  {
    commune: "C2-1",
    name: "Martyris alt",
    in: "gregobase:227",
    gr: "gregobase:1206",
    al: "gregobase:1118",
    tr: "gregobase:1206",
    of: "gregobase:779",
    co: "gregobase:586",
  },
  {
    commune: "C2",
    name: "Martyris",
    in: "gregobase:456",
    gr: "gregobase:827",
    al: "gregobase:1187",
    tr: "gregobase:827",
    of: "gregobase:630",
    co: "gregobase:317",
  },
  {
    commune: "C2a-1",
    name: "Martyris TP alt",
    in: "gregobase:251",
    gr: "gregobase:764",
    al: "gregobase:1201",
    tr: "gregobase:764",
    of: "gregobase:487",
    co: "gregobase:685",
  },
  {
    commune: "C2a",
    name: "Martyris TP",
    in: "gregobase:316",
    gr: "gregobase:153",
    al: "gregobase:1249",
    tr: "gregobase:7670",
    of: "gregobase:407",
    co: "gregobase:89",
  },
  {
    commune: "C2p",
    name: "C2p",
    in: "gregobase:340",
    gr: null,
    al: "gregobase:762",
    tr: null,
    of: "gregobase:1382",
    co: "gregobase:617",
  },
  {
    commune: "C3",
    name: "Martyrum",
    in: "gregobase:261",
    gr: "gregobase:888",
    al: "gregobase:1250",
    tr: "gregobase:888",
    of: "gregobase:919",
    co: "gregobase:658",
  },
  {
    commune: "C3a-1",
    name: "Martyrum TP alt",
    in: "gregobase:737",
    gr: "gregobase:1009",
    al: "gregobase:590",
    tr: "gregobase:1009",
    of: "gregobase:835",
    co: "gregobase:1002",
  },
  {
    commune: "C3a",
    name: "Martyrum TP",
    in: "gregobase:11",
    gr: "gregobase:432",
    al: "gregobase:896",
    tr: "gregobase:432",
    of: "gregobase:33",
    co: "gregobase:699",
  },
  {
    commune: "C3p",
    name: "Martyrum Pont.",
    in: "gregobase:1231",
    gr: null,
    al: "gregobase:106",
    tr: null,
    of: "gregobase:870",
    co: "gregobase:1109",
  },
  {
    commune: "C4-1",
    name: "Conf. Pont. alt",
    in: "gregobase:48",
    gr: "gregobase:415",
    al: "gregobase:1187",
    tr: "gregobase:7670",
    of: "gregobase:630",
    co: "gregobase:1154",
  },
  {
    commune: "C4",
    name: "Conf. Pont.",
    in: "gregobase:456",
    gr: "gregobase:235",
    al: "gregobase:477",
    tr: "gregobase:235",
    of: "gregobase:779",
    co: "gregobase:1008",
  },
  {
    commune: "C4a",
    name: "Doctoris",
    in: "gregobase:233",
    gr: "gregobase:511",
    al: "gregobase:14",
    tr: "gregobase:511",
    of: "gregobase:777",
    co: null,
  },
  {
    commune: "C5-1",
    name: "Virginum alt",
    in: "gregobase:108",
    gr: "gregobase:511",
    al: "gregobase:765",
    tr: "gregobase:511",
    of: "gregobase:667",
    co: "gregobase:1337",
  },
  {
    commune: "C5",
    name: "Virginum",
    in: "gregobase:1374",
    gr: "gregobase:34",
    al: "gregobase:724",
    tr: "gregobase:34",
    of: "gregobase:630",
    co: "gregobase:1154",
  },
  {
    commune: "C5a",
    name: "Virg. Mart.",
    in: "gregobase:233",
    gr: "gregobase:511",
    al: null,
    tr: "gregobase:511",
    of: "gregobase:777",
    co: "gregobase:1008",
  },
  {
    commune: "C5b",
    name: "non Virginum",
    in: "gregobase:1374",
    gr: "gregobase:600",
    al: "gregobase:946",
    tr: "gregobase:600",
    of: "gregobase:722",
    co: "gregobase:1008",
  },
  {
    commune: "C6-1",
    name: "Dedicationis alt",
    in: "gregobase:938",
    gr: "gregobase:1373",
    al: "gregobase:500",
    tr: "gregobase:1373",
    of: "gregobase:177",
    co: "gregobase:844",
  },
  {
    commune: "C6",
    name: "Dedicationis",
    in: "gregobase:510",
    gr: "gregobase:394",
    al: "gregobase:208",
    tr: "gregobase:394",
    of: "gregobase:768",
    co: "gregobase:1032",
  },
  {
    commune: "C6a-1",
    name: "BMV alt",
    in: "gregobase:124",
    gr: "gregobase:686",
    al: "gregobase:500",
    tr: "gregobase:686",
    of: "gregobase:768",
    co: "gregobase:944",
  },
  {
    commune: "C6a",
    name: "BMV",
    in: "gregobase:629",
    gr: "gregobase:174",
    al: "gregobase:208",
    tr: "gregobase:174",
    of: "gregobase:1333",
    co: "gregobase:1301",
  },
  {
    commune: "C7",
    name: "Abbatum",
    in: "gregobase:938",
    gr: "gregobase:394",
    al: "gregobase:406",
    tr: null,
    of: "gregobase:177",
    co: "gregobase:1292",
  },
  {
    commune: "C7a",
    name: "Abbatum alt",
    in: "gregobase:619",
    gr: "gregobase:947",
    al: "gregobase:406",
    tr: "gregobase:947",
    of: null,
    co: "gregobase:799",
  },
  {
    commune: "C8",
    name: "Mart. Pont.",
    in: "gregobase:923",
    gr: "gregobase:651",
    al: "gregobase:242",
    tr: "gregobase:651",
    of: "gregobase:987",
    co: "gregobase:43",
  },
  {
    commune: "C9",
    name: "Commune TP",
    in: "gregobase:766",
    gr: "gregobase:1261",
    al: null,
    tr: null,
    of: "gregobase:1199",
    co: "gregobase:241",
  }
];

export const FEAST_COMMUNE: FeastCommune[] = [
  {
    feastId: "01-11",
    commune: "C4b",
  },
  {
    feastId: "01-14",
    commune: "C4a",
  },
  {
    feastId: "01-15",
    commune: "C5",
  },
  {
    feastId: "01-16",
    commune: "C2b",
  },
  {
    feastId: "01-17",
    commune: "C5b",
  },
  {
    feastId: "01-18",
    commune: "C4",
  },
  {
    feastId: "01-19",
    commune: "C3a",
  },
  {
    feastId: "01-20",
    commune: "C3",
  },
  {
    feastId: "01-21",
    commune: "C6-1",
  },
  {
    feastId: "01-22",
    commune: "C3",
  },
  {
    feastId: "01-23",
    commune: "C5",
  },
  {
    feastId: "01-24",
    commune: "C2",
  },
  {
    feastId: "01-26",
    commune: "C2-1",
  },
  {
    feastId: "01-27",
    commune: "C4a",
  },
  {
    feastId: "01-28",
    commune: "C5-1",
  },
  {
    feastId: "01-29",
    commune: "C4a",
  },
  {
    feastId: "01-30",
    commune: "C6",
  },
  {
    feastId: "01-31",
    commune: "C5",
  },
  {
    feastId: "02-01",
    commune: "C2",
  },
  {
    feastId: "02-02",
    commune: "C11",
  },
  {
    feastId: "02-03",
    commune: "C2-1",
  },
  {
    feastId: "02-04",
    commune: "C4",
  },
  {
    feastId: "02-05",
    commune: "C6",
  },
  {
    feastId: "02-06",
    commune: "C4",
  },
  {
    feastId: "02-07",
    commune: "C5b",
  },
  {
    feastId: "02-08",
    commune: "C5",
  },
  {
    feastId: "02-09",
    commune: "C4a",
  },
  {
    feastId: "02-10",
    commune: "C6a",
  },
  {
    feastId: "02-11",
    commune: "C11",
  },
  {
    feastId: "02-12",
    commune: "C5",
  },
  {
    feastId: "02-14",
    commune: "C2a",
  },
  {
    feastId: "02-15",
    commune: "C3a-1",
  },
  {
    feastId: "02-18",
    commune: "C2",
  },
  {
    feastId: "02-22",
    commune: "C4",
  },
  {
    feastId: "02-24",
    commune: "C1",
  },
  {
    feastId: "02-27",
    commune: "C5",
  },
  {
    feastId: "03-04",
    commune: "C5",
  },
  {
    feastId: "03-06",
    commune: "C7b",
  },
  {
    feastId: "03-07",
    commune: "C5a",
  },
  {
    feastId: "03-08",
    commune: "C5",
  },
  {
    feastId: "03-09",
    commune: "C7a",
  },
  {
    feastId: "03-10",
    commune: "C3",
  },
  {
    feastId: "03-12",
    commune: "C4b",
  },
  {
    feastId: "03-17",
    commune: "C4",
  },
  {
    feastId: "03-18",
    commune: "C4a",
  },
  {
    feastId: "03-21",
    commune: "C5b",
  },
  {
    feastId: "03-25",
    commune: "C11",
  },
  {
    feastId: "03-27",
    commune: "C5",
  },
  {
    feastId: "03-28",
    commune: "C5",
  },
  {
    feastId: "04-02",
    commune: "C5-1",
  },
  {
    feastId: "04-04",
    commune: "C4a",
  },
  {
    feastId: "04-05",
    commune: "C5",
  },
  {
    feastId: "04-11",
    commune: "C4b-2",
  },
  {
    feastId: "04-13",
    commune: "C2a",
  },
  {
    feastId: "04-14",
    commune: "C2a",
  },
  {
    feastId: "04-17",
    commune: "C2b-1",
  },
  {
    feastId: "04-21",
    commune: "C4a",
  },
  {
    feastId: "04-22",
    commune: "C3b",
  },
  {
    feastId: "04-23",
    commune: "C2a",
  },
  {
    feastId: "04-24",
    commune: "C2a",
  },
  {
    feastId: "04-25",
    commune: "C1ap",
  },
  {
    feastId: "04-26",
    commune: "C3b",
  },
  {
    feastId: "04-27",
    commune: "C5a",
  },
  {
    feastId: "04-28",
    commune: "C5",
  },
  {
    feastId: "04-29",
    commune: "C2a-1",
  },
  {
    feastId: "04-30",
    commune: "C6a",
  },
  {
    feastId: "05-01",
    commune: "C1",
  },
  {
    feastId: "05-02",
    commune: "C4a",
  },
  {
    feastId: "05-04",
    commune: "C7a",
  },
  {
    feastId: "05-05",
    commune: "C4b",
  },
  {
    feastId: "05-06",
    commune: "C1",
  },
  {
    feastId: "05-07",
    commune: "C2-1",
  },
  {
    feastId: "05-09",
    commune: "C4a",
  },
  {
    feastId: "05-10",
    commune: "C4",
  },
  {
    feastId: "05-12",
    commune: "C3a-1",
  },
  {
    feastId: "05-13",
    commune: "C4a",
  },
  {
    feastId: "05-14",
    commune: "C2a",
  },
  {
    feastId: "05-15",
    commune: "C5",
  },
  {
    feastId: "05-16",
    commune: "C4",
  },
  {
    feastId: "05-17",
    commune: "C5",
  },
  {
    feastId: "05-18",
    commune: "C2a",
  },
  {
    feastId: "05-19",
    commune: "C4b",
  },
  {
    feastId: "05-20",
    commune: "C5",
  },
  {
    feastId: "05-23",
    commune: "C5",
  },
  {
    feastId: "05-25",
    commune: "C4b",
  },
  {
    feastId: "05-26",
    commune: "C5",
  },
  {
    feastId: "05-27",
    commune: "C5a",
  },
  {
    feastId: "05-28",
    commune: "C4-1",
  },
  {
    feastId: "05-29",
    commune: "C6a",
  },
  {
    feastId: "05-30",
    commune: "C2b",
  },
  {
    feastId: "05-31",
    commune: "C11",
  },
  {
    feastId: "06-01",
    commune: "C6a",
  },
  {
    feastId: "06-02",
    commune: "C3",
  },
  {
    feastId: "06-04",
    commune: "C5",
  },
  {
    feastId: "06-05",
    commune: "C2",
  },
  {
    feastId: "06-06",
    commune: "C4",
  },
  {
    feastId: "06-09",
    commune: "C3a",
  },
  {
    feastId: "06-10",
    commune: "C7a",
  },
  {
    feastId: "06-11",
    commune: "C1",
  },
  {
    feastId: "06-12",
    commune: "C5",
  },
  {
    feastId: "06-13",
    commune: "C5",
  },
  {
    feastId: "06-14",
    commune: "C4a",
  },
  {
    feastId: "06-15",
    commune: "C3",
  },
  {
    feastId: "06-18",
    commune: "C5a",
  },
  {
    feastId: "06-19",
    commune: "C6a",
  },
  {
    feastId: "06-20",
    commune: "C2b",
  },
  {
    feastId: "06-21",
    commune: "C5",
  },
  {
    feastId: "06-22",
    commune: "C4",
  },
  {
    feastId: "06-25",
    commune: "C5b",
  },
  {
    feastId: "06-26",
    commune: "C3",
  },
  {
    feastId: "06-28",
    commune: "C2",
  },
  {
    feastId: "06-29",
    commune: "C1",
  },
  {
    feastId: "06-30",
    commune: "C1",
  },
  {
    feastId: "07-02",
    commune: "C11",
  },
  {
    feastId: "07-03",
    commune: "C4b",
  },
  {
    feastId: "07-05",
    commune: "C5",
  },
  {
    feastId: "07-06",
    commune: "C1",
  },
  {
    feastId: "07-07",
    commune: "C4-1",
  },
  {
    feastId: "07-08",
    commune: "C7a",
  },
  {
    feastId: "07-10",
    commune: "C3",
  },
  {
    feastId: "07-11",
    commune: "C2b",
  },
  {
    feastId: "07-12",
    commune: "C5",
  },
  {
    feastId: "07-13",
    commune: "C4b-1",
  },
  {
    feastId: "07-14",
    commune: "C4a",
  },
  {
    feastId: "07-15",
    commune: "C5",
  },
  {
    feastId: "07-16",
    commune: "C11",
  },
  {
    feastId: "07-17",
    commune: "C5",
  },
  {
    feastId: "07-18",
    commune: "C5",
  },
  {
    feastId: "07-19",
    commune: "C5-1",
  },
  {
    feastId: "07-20",
    commune: "C5",
  },
  {
    feastId: "07-21",
    commune: "C6a",
  },
  {
    feastId: "07-22",
    commune: "C7",
  },
  {
    feastId: "07-23",
    commune: "C2-1",
  },
  {
    feastId: "07-24",
    commune: "C1v",
  },
  {
    feastId: "07-25",
    commune: "C1",
  },
  {
    feastId: "07-26",
    commune: "C7a",
  },
  {
    feastId: "07-27",
    commune: "C2a-1",
  },
  {
    feastId: "07-28",
    commune: "C3",
  },
  {
    feastId: "07-29",
    commune: "C6a",
  },
  {
    feastId: "07-30",
    commune: "C3",
  },
  {
    feastId: "07-31",
    commune: "C5",
  },
  {
    feastId: "08-01",
    commune: "C1",
  },
  {
    feastId: "08-02",
    commune: "C4a",
  },
  {
    feastId: "08-04",
    commune: "C5",
  },
  {
    feastId: "08-05",
    commune: "C11",
  },
  {
    feastId: "08-07",
    commune: "C5",
  },
  {
    feastId: "08-08",
    commune: "C3a-1",
  },
  {
    feastId: "08-09",
    commune: "C5",
  },
  {
    feastId: "08-10",
    commune: "C2a",
  },
  {
    feastId: "08-11",
    commune: "C3a-1",
  },
  {
    feastId: "08-12",
    commune: "C6a",
  },
  {
    feastId: "08-13",
    commune: "C3a-1",
  },
  {
    feastId: "08-15",
    commune: "C11",
  },
  {
    feastId: "08-16",
    commune: "C5",
  },
  {
    feastId: "08-17",
    commune: "C5",
  },
  {
    feastId: "08-19",
    commune: "C5",
  },
  {
    feastId: "08-20",
    commune: "C5a",
  },
  {
    feastId: "08-21",
    commune: "C7a",
  },
  {
    feastId: "08-22",
    commune: "C11",
  },
  {
    feastId: "08-23",
    commune: "C5-1",
  },
  {
    feastId: "08-24",
    commune: "C1",
  },
  {
    feastId: "08-25",
    commune: "C5",
  },
  {
    feastId: "08-26",
    commune: "C2-1b",
  },
  {
    feastId: "08-27",
    commune: "C5",
  },
  {
    feastId: "08-28",
    commune: "C4a",
  },
  {
    feastId: "08-29",
    commune: "C2a",
  },
  {
    feastId: "08-30",
    commune: "C6a",
  },
  {
    feastId: "08-31",
    commune: "C5",
  },
  {
    feastId: "09-01",
    commune: "C5",
  },
  {
    feastId: "09-02",
    commune: "C5",
  },
  {
    feastId: "09-03",
    commune: "C4b",
  },
  {
    feastId: "09-05",
    commune: "C4",
  },
  {
    feastId: "09-08",
    commune: "C11",
  },
  {
    feastId: "09-09",
    commune: "C2a-1",
  },
  {
    feastId: "09-10",
    commune: "C5-1",
  },
  {
    feastId: "09-11",
    commune: "C3a-1",
  },
  {
    feastId: "09-12",
    commune: "C11",
  },
  {
    feastId: "09-15",
    commune: "C11",
  },
  {
    feastId: "09-16",
    commune: "C3",
  },
  {
    feastId: "09-17",
    commune: "C5",
  },
  {
    feastId: "09-18",
    commune: "C5",
  },
  {
    feastId: "09-19",
    commune: "C3a-1",
  },
  {
    feastId: "09-20",
    commune: "C3a",
  },
  {
    feastId: "09-21",
    commune: "C1a",
  },
  {
    feastId: "09-22",
    commune: "C4",
  },
  {
    feastId: "09-23",
    commune: "C2b-1",
  },
  {
    feastId: "09-24",
    commune: "C11",
  },
  {
    feastId: "09-26",
    commune: "C3a-1",
  },
  {
    feastId: "09-27",
    commune: "C3a",
  },
  {
    feastId: "09-28",
    commune: "C2a",
  },
  {
    feastId: "09-30",
    commune: "C5a",
  },
  {
    feastId: "10-01",
    commune: "C4",
  },
  {
    feastId: "10-02",
    commune: "C4",
  },
  {
    feastId: "10-03",
    commune: "C6a",
  },
  {
    feastId: "10-04",
    commune: "C5",
  },
  {
    feastId: "10-05",
    commune: "C3a-1",
  },
  {
    feastId: "10-06",
    commune: "C5",
  },
  {
    feastId: "10-07",
    commune: "C11",
  },
  {
    feastId: "10-08",
    commune: "C7a",
  },
  {
    feastId: "10-09",
    commune: "C5",
  },
  {
    feastId: "10-10",
    commune: "C5b",
  },
  {
    feastId: "10-11",
    commune: "C11",
  },
  {
    feastId: "10-13",
    commune: "C5",
  },
  {
    feastId: "10-14",
    commune: "C2b",
  },
  {
    feastId: "10-15",
    commune: "C6a",
  },
  {
    feastId: "10-16",
    commune: "C7a",
  },
  {
    feastId: "10-17",
    commune: "C6a",
  },
  {
    feastId: "10-18",
    commune: "C1a",
  },
  {
    feastId: "10-19",
    commune: "C5-1",
  },
  {
    feastId: "10-20",
    commune: "C5",
  },
  {
    feastId: "10-21",
    commune: "C5b",
  },
  {
    feastId: "10-25",
    commune: "C3",
  },
  {
    feastId: "10-26",
    commune: "C2b",
  },
  {
    feastId: "10-27",
    commune: "C1v",
  },
  {
    feastId: "10-28",
    commune: "C1",
  },
  {
    feastId: "11-01",
    commune: "C3",
  },
  {
    feastId: "11-02",
    commune: "C9",
  },
  {
    feastId: "11-04",
    commune: "C4",
  },
  {
    feastId: "11-09",
    commune: "C8",
  },
  {
    feastId: "11-10",
    commune: "C5",
  },
  {
    feastId: "11-11",
    commune: "C4",
  },
  {
    feastId: "11-12",
    commune: "C2b-1",
  },
  {
    feastId: "11-13",
    commune: "C5-1",
  },
  {
    feastId: "11-14",
    commune: "C2",
  },
  {
    feastId: "11-15",
    commune: "C4a",
  },
  {
    feastId: "11-16",
    commune: "C6a",
  },
  {
    feastId: "11-17",
    commune: "C4",
  },
  {
    feastId: "11-18",
    commune: "C8",
  },
  {
    feastId: "11-19",
    commune: "C7a",
  },
  {
    feastId: "11-20",
    commune: "C5-1",
  },
  {
    feastId: "11-21",
    commune: "C11",
  },
  {
    feastId: "11-22",
    commune: "C6",
  },
  {
    feastId: "11-23",
    commune: "C2b",
  },
  {
    feastId: "11-24",
    commune: "C5a",
  },
  {
    feastId: "11-25",
    commune: "C6",
  },
  {
    feastId: "11-26",
    commune: "C5b",
  },
  {
    feastId: "11-29",
    commune: "C1v",
  },
  {
    feastId: "11-30",
    commune: "C1",
  },
  {
    feastId: "12-02",
    commune: "C6-1",
  },
  {
    feastId: "12-03",
    commune: "C5-1",
  },
  {
    feastId: "12-04",
    commune: "C4a",
  },
  {
    feastId: "12-05",
    commune: "C5b",
  },
  {
    feastId: "12-06",
    commune: "C4",
  },
  {
    feastId: "12-07",
    commune: "C4a",
  },
  {
    feastId: "12-08",
    commune: "C11",
  },
  {
    feastId: "12-11",
    commune: "C4b",
  },
  {
    feastId: "12-13",
    commune: "C6",
  },
  {
    feastId: "12-16",
    commune: "C2-1",
  },
  {
    feastId: "12-21",
    commune: "C1",
  },
  {
    feastId: "12-26",
    commune: "C2a",
  },
  {
    feastId: "12-27",
    commune: "C1",
  },
  {
    feastId: "12-28",
    commune: "C3",
  },
  {
    feastId: "12-29",
    commune: "C2-1",
  },
  {
    feastId: "12-31",
    commune: "C4b",
  }
];
