// AUTO-GENERATED by scripts/match-office-antiphons.mjs — do not edit manually
// The ferial (weekday) office antiphon cycle, mined from DO's psalter.
// 208 slots across 8 hours.

import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

/** hour → weekday ("0".."6" | "any") → variant → chant ids, in ord order. */
export type FerialTable = Record<string, Record<string, Record<string, string[]>>>;

const __dir = dirname(fileURLToPath(import.meta.url));
export const OFFICE_FERIAL: FerialTable = (
  JSON.parse(readFileSync(resolve(__dir, "office-ferial.json"), "utf8")) as {
    table: FerialTable;
  }
).table;
