// AUTO-GENERATED by scripts/extract-psalms.mjs — do not edit manually
// Generated: 2026-03-28T23:14:44.175Z
// 2612 psalm verses + 579 canticle verses from DO Psalterium

import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { PsalmVerse } from "./types.js";

export type { PsalmVerse };

const __dir = dirname(fileURLToPath(import.meta.url));
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const PSALMS: PsalmVerse[] = JSON.parse(readFileSync(resolve(__dir, "psalms.json"), "utf8")) as PsalmVerse[];
