// AUTO-GENERATED by scripts/extract-seasonal-respbreve.mjs — do not edit manually
// The little hours' short responsory, which is SEASONAL rather than proper to
// a feast: DO keeps it in Psalterium/Special keyed by tempus, and carries none
// at all in SanctiM/TemporaM.

import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

/** tempus → hour → chant id. `feria`/`dominica` are the per-diem default,
 *  chosen by weekday; the rest are seasons. */
export type SeasonalRespBreve = Record<string, Record<string, string>>;

const __dir = dirname(fileURLToPath(import.meta.url));
export const SEASONAL_RESPBREVE: SeasonalRespBreve = (
  JSON.parse(readFileSync(resolve(__dir, "seasonal-respbreve.json"), "utf8")) as {
    map: SeasonalRespBreve;
  }
).map;
