// ---------------------------------------------------------------------------
// data/smufl-glyphs — SMuFL chant glyph outlines (baked from Bravura)
// ---------------------------------------------------------------------------
// Generated by scripts/extract-smufl-glyphs.py — do not edit smufl-glyphs.json
// by hand. Paths are in font units, y-up (baseline at 0); the SVG emitter
// applies scale(s, -s). See the script header for the coordinate contract.

import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

export interface SmuflGlyph {
  /** SVG path `d` in font units, y-up. */
  path: string;
  /** Advance width in font units. */
  advance: number;
  /** Ink bounds [xMin, yMin, xMax, yMax] in font units, y-up. */
  bbox: [number, number, number, number];
}

interface SmuflGlyphFile {
  meta: { upm: number; count: number; [k: string]: unknown };
  glyphs: Record<string, SmuflGlyph>;
}

const __dir = dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(
  readFileSync(resolve(__dir, "smufl-glyphs.json"), "utf8"),
) as SmuflGlyphFile;

/** Units per em for the baked outlines (all coordinates are in these units). */
export const GLYPH_UPM = data.meta.upm;

/** codepoint hex (e.g. "E990") → { path, advance }. */
export const GLYPHS: Readonly<Record<string, SmuflGlyph>> = data.glyphs;

/** Look up a glyph by codepoint hex; null if absent. */
export function glyph(codepoint: string): SmuflGlyph | null {
  return GLYPHS[codepoint] ?? null;
}
